//! Emit Elmer's Solver Input File (`.sif`) format from a typed
//! [`ElmerInput`].
//!
//! Structure of a minimal heat-equation SIF, which is what we emit
//! today:
//!
//! ```text
//! Header
//!   Mesh DB "." "mesh"
//! End
//!
//! Simulation
//!   Max Output Level = 5
//!   Coordinate System = Cartesian
//!   Simulation Type = Steady State
//!   Steady State Max Iterations = 20
//!   Output File = "case.result"
//!   Post File = "case.vtu"
//! End
//!
//! Constants
//!   Stefan Boltzmann = 5.67e-08
//! End
//!
//! Body 1
//!   Target Bodies(1) = 1
//!   Equation = 1
//!   Material = 1
//! End
//!
//! Solver 1
//!   Equation = Heat Equation
//!   Variable = Temperature
//!   Linear System Solver = Iterative
//!   Linear System Iterative Method = BiCGStab
//!   Linear System Convergence Tolerance = 1.0e-8
//!   Steady State Convergence Tolerance = 1.0e-5
//! End
//!
//! Equation 1
//!   Name = "Heat"
//!   Active Solvers(1) = 1
//! End
//!
//! Material 1
//!   Name = "Aluminium"
//!   Density = 2700
//!   Heat Capacity = 897
//!   Heat Conductivity = 237
//! End
//!
//! Boundary Condition 1
//!   Target Boundaries(1) = 1
//!   Name = "inlet"
//!   Temperature = 350
//! End
//! ```

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use valenx_core::adapter_helpers::sanitize_structured_identifier;

use crate::case_input::{BoundaryCondition, ElmerInput, Equation, TimeMode};

pub const DEFAULT_SIF_FILENAME: &str = "case.sif";

pub fn generate(input: &ElmerInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "! Generated by valenx-adapter-elmer — do not edit by hand.\n"
    )
    .unwrap();

    write_header(&mut s, input);
    writeln!(s).unwrap();
    write_simulation(&mut s, input);
    writeln!(s).unwrap();
    write_constants(&mut s);
    writeln!(s).unwrap();
    write_body(&mut s, input);
    writeln!(s).unwrap();
    write_solver(&mut s, input);
    writeln!(s).unwrap();
    write_equation(&mut s, input);
    writeln!(s).unwrap();
    write_material(&mut s, input);
    writeln!(s).unwrap();
    // Initial Condition block — only emitted when the user supplied
    // an initial_temperature. Elmer attaches it via `Initial Condition
    // = 1` on the Body block, which `write_body` adds when this is
    // present.
    if input.initial_temperature.is_some() {
        write_initial_condition(&mut s, input);
        writeln!(s).unwrap();
    }
    for (i, bc) in input.boundaries.iter().enumerate() {
        write_boundary_condition(&mut s, i + 1, bc);
        writeln!(s).unwrap();
    }

    s
}

fn write_header(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Header").unwrap();
    writeln!(s, "  CHECK KEYWORDS Warn").unwrap();
    // Round-15 M1: sanitise every char that can break out of the
    // quoted literal. `mesh_dir` is a user-supplied PathBuf and
    // pre-fix Path::display() would emit raw `"`/`\n`/`\\` chars,
    // letting a hostile case.toml inject sibling Header / Solver
    // directives via the mesh_dir field. Sister of round-14's IFC
    // ifc_str escape.
    let mesh_dir = sanitize_structured_identifier(&input.mesh_dir.display().to_string());
    writeln!(s, "  Mesh DB \".\" \"{mesh_dir}\"").unwrap();
    writeln!(s, "  Include Path \"\"").unwrap();
    writeln!(s, "  Results Directory \"\"").unwrap();
    writeln!(s, "End").unwrap();
}

fn write_simulation(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Simulation").unwrap();
    writeln!(
        s,
        "  Max Output Level = {}",
        input.simulation.max_output_level
    )
    .unwrap();
    writeln!(s, "  Coordinate System = Cartesian").unwrap();
    writeln!(s, "  Coordinate Mapping(3) = 1 2 3").unwrap();
    writeln!(s, "  Simulation Type = {}", input.time.simulation_type()).unwrap();
    writeln!(
        s,
        "  Steady State Max Iterations = {}",
        input.simulation.steady_state_max_iterations
    )
    .unwrap();
    match input.time {
        TimeMode::Steady => {
            // Steady runs only need the iteration cap above. The
            // BDF lines used to be unconditional, but Elmer's parser
            // prints a warning when `Timestep Sizes` is absent in a
            // Transient run AND when it's set to a meaningless value
            // in a Steady run — so omit them entirely here.
            writeln!(s, "  Output Intervals = 1").unwrap();
        }
        TimeMode::Transient { end_time, delta_t } => {
            // Transient: BDF integrator, second-order is the safe
            // default for diffusive problems. Number-of-intervals
            // derives from end_time / delta_t (rounded up so we
            // always reach end_time, never under-shoot it).
            let intervals = ((end_time / delta_t).ceil() as i64).max(1);
            writeln!(s, "  Timestepping Method = BDF").unwrap();
            writeln!(s, "  BDF Order = 2").unwrap();
            writeln!(s, "  Timestep Intervals = {intervals}").unwrap();
            writeln!(s, "  Timestep Sizes = {delta_t:.6e}").unwrap();
            // Write every step. Decimation can land later if users
            // start to feel disk-bound; for typical small-enough
            // cases every-step output keeps the chart honest.
            writeln!(s, "  Output Intervals = 1").unwrap();
        }
    }
    writeln!(s, "  Solver Input File = case.sif").unwrap();
    // Round-15 M1: same sanitisation treatment as `mesh_dir`. A
    // hostile output_basename like `x"\nMaterial 99\n  Name = "x"\nEnd`
    // would otherwise close the Output File literal and inject a
    // sibling Material block that silently swaps the thermal
    // conductivity at run time.
    let basename = sanitize_structured_identifier(&input.output_basename);
    writeln!(s, "  Output File = \"{basename}.result\"").unwrap();
    writeln!(s, "  Post File = \"{basename}.vtu\"").unwrap();
    writeln!(s, "End").unwrap();
}

fn write_constants(s: &mut String) {
    writeln!(s, "Constants").unwrap();
    writeln!(s, "  Gravity(4) = 0 -1 0 9.82").unwrap();
    writeln!(s, "  Stefan Boltzmann = 5.670374419e-08").unwrap();
    writeln!(s, "  Permittivity of Vacuum = 8.8541878128e-12").unwrap();
    writeln!(s, "  Permeability of Vacuum = 1.25663706212e-6").unwrap();
    writeln!(s, "  Boltzmann Constant = 1.380649e-23").unwrap();
    writeln!(s, "  Unit Charge = 1.602176634e-19").unwrap();
    writeln!(s, "End").unwrap();
}

fn write_body(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Body 1").unwrap();
    writeln!(s, "  Target Bodies(1) = 1").unwrap();
    writeln!(s, "  Name = \"Body 1\"").unwrap();
    writeln!(s, "  Equation = 1").unwrap();
    writeln!(s, "  Material = 1").unwrap();
    if input.initial_temperature.is_some() {
        // Reference the Initial Condition block written below; without
        // this line Elmer ignores the IC entirely and starts from 0,
        // which is rarely what the user wanted.
        writeln!(s, "  Initial Condition = 1").unwrap();
    }
    writeln!(s, "End").unwrap();
}

fn write_initial_condition(s: &mut String, input: &ElmerInput) {
    let t0 = input
        .initial_temperature
        .expect("caller checked that initial_temperature is Some");
    writeln!(s, "Initial Condition 1").unwrap();
    writeln!(s, "  Name = \"InitialState\"").unwrap();
    match input.equation {
        Equation::HeatEquation => {
            writeln!(s, "  Temperature = {t0:.6e}").unwrap();
        }
    }
    writeln!(s, "End").unwrap();
}

fn write_solver(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Solver 1").unwrap();
    match input.equation {
        Equation::HeatEquation => {
            writeln!(s, "  Equation = Heat Equation").unwrap();
            writeln!(s, "  Variable = Temperature").unwrap();
            writeln!(s, "  Variable Dofs = 1").unwrap();
            writeln!(s, "  Procedure = \"HeatSolve\" \"HeatSolver\"").unwrap();
        }
    }
    writeln!(s, "  Calculate Loads = True").unwrap();
    writeln!(s, "  Exec Solver = Always").unwrap();
    writeln!(s, "  Stabilize = True").unwrap();
    writeln!(s, "  Bubbles = False").unwrap();
    writeln!(s, "  Optimize Bandwidth = True").unwrap();
    writeln!(
        s,
        "  Steady State Convergence Tolerance = {:.6e}",
        input.simulation.convergence_tolerance
    )
    .unwrap();
    writeln!(s, "  Nonlinear System Convergence Tolerance = 1.0e-7").unwrap();
    writeln!(s, "  Nonlinear System Max Iterations = 20").unwrap();
    writeln!(s, "  Nonlinear System Newton After Iterations = 3").unwrap();
    writeln!(s, "  Nonlinear System Newton After Tolerance = 1.0e-3").unwrap();
    writeln!(s, "  Nonlinear System Relaxation Factor = 1").unwrap();
    writeln!(s, "  Linear System Solver = Iterative").unwrap();
    writeln!(s, "  Linear System Iterative Method = BiCGStab").unwrap();
    writeln!(s, "  Linear System Max Iterations = 500").unwrap();
    writeln!(s, "  Linear System Convergence Tolerance = 1.0e-8").unwrap();
    writeln!(s, "  Linear System Preconditioning = ILU0").unwrap();
    writeln!(s, "  Linear System ILUT Tolerance = 1.0e-3").unwrap();
    writeln!(s, "  Linear System Abort Not Converged = False").unwrap();
    writeln!(s, "  Linear System Residual Output = 1").unwrap();
    writeln!(s, "End").unwrap();
}

fn write_equation(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Equation 1").unwrap();
    let name = match input.equation {
        Equation::HeatEquation => "Heat",
    };
    writeln!(s, "  Name = \"{name}\"").unwrap();
    writeln!(s, "  Active Solvers(1) = 1").unwrap();
    writeln!(s, "End").unwrap();
}

fn write_material(s: &mut String, input: &ElmerInput) {
    writeln!(s, "Material 1").unwrap();
    // Round-15 M1: see write_simulation / write_header. material.name
    // is user-supplied via case.toml and was previously interpolated
    // raw — a `"\nBoundary Condition 999\n…"` payload would close the
    // Name literal and inject a sibling BC that silently overrides
    // the real one.
    let name = sanitize_structured_identifier(&input.material.name);
    writeln!(s, "  Name = \"{name}\"").unwrap();
    writeln!(s, "  Density = {:.6e}", input.material.density).unwrap();
    writeln!(s, "  Heat Capacity = {:.6e}", input.material.heat_capacity).unwrap();
    writeln!(
        s,
        "  Heat Conductivity = {:.6e}",
        input.material.heat_conductivity
    )
    .unwrap();
    writeln!(s, "End").unwrap();
}

fn write_boundary_condition(s: &mut String, id: usize, bc: &BoundaryCondition) {
    writeln!(s, "Boundary Condition {id}").unwrap();
    // Round-15 M1: BC name comes from case.toml and was previously
    // interpolated raw into the `Name = "..."` literal — see
    // write_material for the injection mechanism. Sanitise both
    // arms (Temperature + HeatFlux) consistently.
    match bc {
        BoundaryCondition::Temperature {
            name,
            target,
            value,
        } => {
            writeln!(s, "  Target Boundaries(1) = {target}").unwrap();
            let name = sanitize_structured_identifier(name);
            writeln!(s, "  Name = \"{name}\"").unwrap();
            writeln!(s, "  Temperature = {value:.6e}").unwrap();
        }
        BoundaryCondition::HeatFlux {
            name,
            target,
            value,
        } => {
            writeln!(s, "  Target Boundaries(1) = {target}").unwrap();
            let name = sanitize_structured_identifier(name);
            writeln!(s, "  Name = \"{name}\"").unwrap();
            writeln!(s, "  Heat Flux = {value:.6e}").unwrap();
        }
    }
    writeln!(s, "End").unwrap();
}

pub fn write_to_file(input: &ElmerInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{BoundaryCondition, ElmerInput, Material, Simulation};

    fn sample_input() -> ElmerInput {
        ElmerInput {
            equation: Equation::HeatEquation,
            mesh_dir: std::path::PathBuf::from("mesh"),
            material: Material {
                name: "aluminium".into(),
                density: 2700.0,
                heat_capacity: 897.0,
                heat_conductivity: 237.0,
            },
            boundaries: vec![
                BoundaryCondition::Temperature {
                    name: "inlet".into(),
                    target: 1,
                    value: 350.0,
                },
                BoundaryCondition::HeatFlux {
                    name: "outlet".into(),
                    target: 2,
                    value: 0.0,
                },
            ],
            simulation: Simulation::default(),
            output_basename: "case".into(),
            time: TimeMode::Steady,
            initial_temperature: None,
        }
    }

    #[test]
    fn sif_has_expected_blocks() {
        let sif = generate(&sample_input());
        // Structural blocks.
        assert!(sif.contains("Header"));
        assert!(sif.contains("Simulation"));
        assert!(sif.contains("Constants"));
        assert!(sif.contains("Body 1"));
        assert!(sif.contains("Solver 1"));
        assert!(sif.contains("Equation 1"));
        assert!(sif.contains("Material 1"));
        // Multiple Boundary Condition blocks.
        assert!(sif.contains("Boundary Condition 1"));
        assert!(sif.contains("Boundary Condition 2"));
        // Solver specifics.
        assert!(sif.contains("Equation = Heat Equation"));
        assert!(sif.contains("Variable = Temperature"));
        // Material values in scientific form.
        assert!(sif.contains("Density = 2.700000e3"));
        assert!(sif.contains("Heat Conductivity = 2.370000e2"));
        // BC values.
        assert!(sif.contains("Temperature = 3.500000e2"));
        assert!(sif.contains("Heat Flux = 0.000000e0"));
    }

    #[test]
    fn sif_mesh_db_uses_configured_dir() {
        let mut input = sample_input();
        input.mesh_dir = std::path::PathBuf::from("my-mesh");
        let sif = generate(&input);
        assert!(sif.contains("Mesh DB \".\" \"my-mesh\""));
    }

    #[test]
    fn sif_post_file_uses_basename() {
        let mut input = sample_input();
        input.output_basename = "heatsink".into();
        let sif = generate(&input);
        assert!(sif.contains("Output File = \"heatsink.result\""));
        assert!(sif.contains("Post File = \"heatsink.vtu\""));
    }

    #[test]
    fn sif_bc_numbering_starts_at_one() {
        let sif = generate(&sample_input());
        // First BC always gets id 1; content-assert the text block.
        assert!(sif.contains("Boundary Condition 1\n  Target Boundaries(1) = 1"));
        assert!(sif.contains("Boundary Condition 2\n  Target Boundaries(1) = 2"));
    }

    #[test]
    fn steady_sif_omits_transient_bdf_lines() {
        // Steady runs no longer dump `Timestepping Method = BDF`
        // unconditionally — those lines have meaning only for
        // transient runs and Elmer warns when they appear in a steady
        // configuration (older versions even errored on conflicting
        // settings).
        let sif = generate(&sample_input());
        assert!(sif.contains("Simulation Type = Steady State"));
        assert!(
            !sif.contains("Timestep Sizes"),
            "steady run leaked a Timestep Sizes line: {sif}"
        );
        assert!(
            !sif.contains("Timestep Intervals"),
            "steady run leaked a Timestep Intervals line: {sif}"
        );
    }

    #[test]
    fn transient_sif_writes_bdf_intervals_and_initial_condition() {
        let mut input = sample_input();
        input.time = TimeMode::Transient {
            end_time: 60.0,
            delta_t: 0.1,
        };
        input.initial_temperature = Some(600.0);
        let sif = generate(&input);

        // Simulation block: Transient + BDF integrator + interval count.
        assert!(sif.contains("Simulation Type = Transient"));
        assert!(sif.contains("Timestepping Method = BDF"));
        assert!(sif.contains("BDF Order = 2"));
        // 60.0 / 0.1 = 600 intervals.
        assert!(
            sif.contains("Timestep Intervals = 600"),
            "expected 600 intervals (60s/0.1s): {sif}"
        );
        assert!(
            sif.contains("Timestep Sizes = 1.000000e-1")
                || sif.contains("Timestep Sizes = 1.000000e-01"),
            "expected delta_t = 0.1: {sif}"
        );

        // Initial Condition block + Body reference.
        assert!(
            sif.contains("Initial Condition 1\n  Name = \"InitialState\""),
            "missing Initial Condition block: {sif}"
        );
        assert!(
            sif.contains("Temperature = 6.000000e2") || sif.contains("Temperature = 6.000000e02"),
            "expected T0 = 600.0: {sif}"
        );
        assert!(
            sif.contains("Body 1\n  Target Bodies(1) = 1\n  Name = \"Body 1\"\n  Equation = 1\n  Material = 1\n  Initial Condition = 1"),
            "Body block must reference Initial Condition 1: {sif}"
        );
    }

    #[test]
    fn transient_intervals_round_up_for_uneven_division() {
        // 1.0 / 0.3 = 3.333… → 4 intervals (round up so we always
        // reach end_time, never under-shoot).
        let mut input = sample_input();
        input.time = TimeMode::Transient {
            end_time: 1.0,
            delta_t: 0.3,
        };
        let sif = generate(&input);
        assert!(
            sif.contains("Timestep Intervals = 4"),
            "expected 4 intervals from ceil(1.0/0.3): {sif}"
        );
    }

    #[test]
    fn steady_with_initial_temperature_still_emits_block() {
        // We don't gate the IC block on time mode — users sometimes
        // want it written into steady SIFs as a hint for downstream
        // tooling, and Elmer will simply ignore it for steady solves.
        let mut input = sample_input();
        input.initial_temperature = Some(293.15);
        let sif = generate(&input);
        assert!(sif.contains("Initial Condition 1"));
        assert!(sif.contains("Initial Condition = 1")); // body ref
    }

    // -----------------------------------------------------------------
    // Round-15 M1 RED→GREEN: SIF identifier-injection via output_basename
    // / material.name / BC.name / mesh_dir. Sister to round-14's IFC
    // `ifc_str` Part-21 escape — every string the SIF writer
    // interpolates into a quoted literal needs the same sanitisation
    // treatment.
    // -----------------------------------------------------------------

    #[test]
    fn sif_output_basename_injection_attempt_is_neutralised() {
        // Pre-fix payload: a hostile output_basename closes the
        // `Output File = "..."` literal, opens a sibling Material 99
        // block (which Elmer would happily honour, silently replacing
        // the real material thermal-conductivity at run time), and
        // leaves a dangling tail. After the sanitiser pass the
        // injection chars (`\n`, `"`) get stripped, so the payload
        // collapses into a single (very ugly) filename — the writer
        // emits a still-syntactically-valid `Output File = "…"` block
        // and no sibling Material block ever opens.
        let mut input = sample_input();
        input.output_basename =
            "x\"\nMaterial 99\n  Name = \"injected\"\nEnd\n".into();
        let sif = generate(&input);
        // The exact pre-fix attack: a fresh line opening `Material 99`.
        assert!(
            !sif.contains("\nMaterial 99"),
            "injection opened a sibling Material 99 block at column 0: {sif}"
        );
        // The escape chars themselves must be gone from the
        // interpolated literal so the closing `"` stays paired.
        let output_file_lines: Vec<&str> =
            sif.lines().filter(|l| l.contains("Output File")).collect();
        for line in &output_file_lines {
            assert!(
                !line.contains('\\'),
                "Output File line still contains a backslash escape: {line}"
            );
            // Each Output File line must have exactly two `"` chars
            // (the opening and closing quote). Anything else means a
            // payload char leaked out.
            assert_eq!(
                line.matches('"').count(),
                2,
                "Output File line has unbalanced quotes: {line}"
            );
        }
    }

    #[test]
    fn sif_material_name_injection_attempt_is_neutralised() {
        // Material name injection: closes `Name = "..."`, opens a
        // Boundary Condition 999 block that silently overrides the
        // real BC on patch 1 with a different temperature. After the
        // sanitiser the payload chars collapse into the Name literal
        // — the sibling block at column 0 never appears.
        let mut input = sample_input();
        input.material.name = "X\"\nBoundary Condition 999\n  Target Boundaries(1) = 1\n  Temperature = 9999\nEnd\n".into();
        let sif = generate(&input);
        // No fresh BC block opened at column 0 by the injection.
        assert!(
            !sif.contains("\nBoundary Condition 999"),
            "material.name injection opened sibling BC 999 block: {sif}"
        );
        // The Material block's Name line must be a single well-formed
        // line with paired quotes.
        let name_lines: Vec<&str> = sif
            .lines()
            .filter(|l| l.starts_with("  Name = \""))
            .collect();
        for line in &name_lines {
            assert_eq!(
                line.matches('"').count(),
                2,
                "Name line has unbalanced quotes: {line}"
            );
        }
    }

    #[test]
    fn sif_boundary_condition_name_injection_attempt_is_neutralised() {
        // BC Name field injection: closes the `Name = "..."` literal
        // and opens a Solver 99 block that swaps the heat solver for
        // a no-op procedure, silently producing zero-output runs.
        let mut input = sample_input();
        if let BoundaryCondition::Temperature { name, .. } = &mut input.boundaries[0] {
            *name = "y\"\nSolver 99\n  Equation = NoOp\nEnd\n".into();
        }
        let sif = generate(&input);
        // No fresh Solver 99 block opened at column 0.
        assert!(
            !sif.contains("\nSolver 99"),
            "BC.name injection opened sibling Solver 99 block: {sif}"
        );
        // The BC's Name line stays a single well-formed line with
        // paired quotes (the safe collapse). A fresh column-0
        // `  Equation = NoOp` directive must NOT appear (the leading
        // two-space indent is the SIF block-member convention).
        // Note: the literal substring `Equation = NoOp` will still
        // appear inside the now-collapsed Name = "..." literal — that's
        // benign, not a directive. Pin column-0 / indent-0 specifically.
        assert!(
            !sif.lines().any(|l| l.starts_with("  Equation = NoOp")),
            "injected Equation directive opened as Solver block child: {sif}"
        );
    }

    #[test]
    fn sif_mesh_db_injection_attempt_is_neutralised() {
        // mesh_dir is a PathBuf so quote / newline injection needs a
        // crafted path. The sanitiser strips the embedded `"` + `\n`
        // before Mesh DB interpolates, so the closing literal stays
        // paired and no Solver Input File override sneaks in.
        let mut input = sample_input();
        input.mesh_dir =
            std::path::PathBuf::from("mesh\"\n  Solver Input File = \"/tmp/pwn\"");
        let sif = generate(&input);
        // No fresh override directive opened at column 2 (inside the
        // Header block) by the injection.
        assert!(
            !sif.contains("\n  Solver Input File = \"/tmp/pwn\""),
            "mesh_dir injection opened sibling directive: {sif}"
        );
        // The Mesh DB line itself must have balanced quotes (the two
        // outer quotes + the inner literal quote-pair from `.` and
        // `<mesh_dir>` — 4 total).
        let mesh_db_lines: Vec<&str> =
            sif.lines().filter(|l| l.contains("Mesh DB")).collect();
        for line in &mesh_db_lines {
            assert_eq!(
                line.matches('"').count(),
                4,
                "Mesh DB line has unbalanced quotes: {line}"
            );
        }
    }
}
