//! Lock-in test: the case.toml shape that `valenx-init --template
//! gmsh` writes must parse cleanly through the gmsh adapter's
//! `mesh_input` module.

use valenx_adapter_gmsh::mesh_input::{Domain, MeshSpec};
use valenx_core::CaseDef;

const TEMPLATE_CASE_TOML: &str = r#"# Generated by `valenx-init`. Edit freely.
[case]
format  = "1.0"
name    = "box-mesh"
physics = "meshing"
solver  = "gmsh.delaunay"
mesh    = "primary"

# Procedural box mesh — gmsh's built-in meshers handle this without
# any external geometry file. Switch `type` to "sphere" or
# "merge" to import an external `.stl` / `.brep` / `.step`.
[mesh]
type                  = "box"
origin                = [0.0, 0.0, 0.0]
size                  = [1.0, 1.0, 1.0]
characteristic_length = 0.1
algorithm_3d          = "delaunay"
dim                   = 3
volume_name           = "fluid"
surface_name          = "walls"
"#;

#[test]
fn gmsh_template_case_toml_parses_through_adapter() {
    let case_def: CaseDef =
        toml::from_str(TEMPLATE_CASE_TOML).expect("template case.toml is valid TOML");
    let spec = MeshSpec::from_case_def(&case_def).expect("parses through gmsh adapter");

    match spec.domain {
        Domain::Box { origin, size } => {
            for axis in 0..3 {
                assert!((origin[axis] - 0.0).abs() < 1e-9);
                assert!((size[axis] - 1.0).abs() < 1e-9);
            }
        }
        other => panic!("expected Box; got {other:?}"),
    }
    // `characteristic_length = 0.1` rolls into char_length_max via
    // the parser's alias chain.
    assert!((spec.sizes.char_length_max - 0.1).abs() < 1e-9);
}
