//! Lock-in test: the case.toml shape that `valenx-init --template
//! lammps` writes must parse cleanly through the LAMMPS adapter's
//! `case_input` module.
//!
//! This file deliberately duplicates the case.toml body the template
//! emits — drift between the template and this test surfaces as
//! either a parse failure (the test catches the regression) or
//! divergent text (a careful reviewer catches the staleness during
//! code review). Pre-existing per-adapter `case_input` unit tests
//! exercise hand-written TOML; this is the first one that pins the
//! exact shape `valenx-init` users see.

use valenx_adapter_lammps::case_input::{Ensemble, LammpsInput, Potential};
use valenx_core::CaseDef;

const TEMPLATE_CASE_TOML: &str = r#"# Generated by `valenx-init`. Edit freely.
[case]
format  = "1.0"
name    = "lj-fluid"
physics = "molecular-dynamics"
solver  = "lammps.nve"
mesh    = "(none)"

# Lennard-Jones FCC fluid in NVE — the canonical "does my LAMMPS
# build work" smoke run. Edit `density`, `size`, `run_steps` to
# scale to your hardware.
[md]
units        = "lj"
atom_style   = "atomic"
boundary     = ["p", "p", "p"]
timestep     = 0.005
run_steps    = 2000
initial_temperature = 1.0
thermo_every = 50
dump_every   = 100
ensemble     = "nve"

[md.init]
kind      = "lj-fcc-box"
density   = 0.8442
size      = [10, 10, 10]
num_types = 1

[md.potential]
kind    = "lj-cut"
epsilon = 1.0
sigma   = 1.0
cutoff  = 2.5
"#;

#[test]
fn lammps_template_case_toml_parses_through_adapter() {
    let case_def: CaseDef =
        toml::from_str(TEMPLATE_CASE_TOML).expect("template case.toml is valid TOML");
    let input = LammpsInput::from_case_def(&case_def).expect("parses through LAMMPS adapter");

    // Spot-check the fields the template populates so a future edit
    // that drops one (typo'd `kind`, missing `[md.init]`, etc.)
    // surfaces here as a precise failure rather than a generic parse
    // error.
    assert!(matches!(input.ensemble, Ensemble::Nve));
    assert_eq!(input.run_steps, 2000);
    assert!((input.timestep - 0.005).abs() < 1e-9);
    assert!((input.initial_temperature.unwrap_or(0.0) - 1.0).abs() < 1e-9);
    match input.potential {
        Potential::LjCut {
            epsilon,
            sigma,
            cutoff,
        } => {
            assert!((epsilon - 1.0).abs() < 1e-9);
            assert!((sigma - 1.0).abs() < 1e-9);
            assert!((cutoff - 2.5).abs() < 1e-9);
        }
        other => panic!("expected LjCut potential; got {other:?}"),
    }
}
