//! Phase 122 — extended PLY writer (vertex colours + normals).
//!
//! ## What OCCT does
//!
//! `RWPly_CafWriter` walks the BRep, tessellates, and emits PLY
//! with per-vertex normals (`property float nx ny nz`), per-vertex
//! colours (`property uchar red green blue`), and (optionally)
//! per-face material indices. This matches the
//! Stanford-PLY-extended convention every modern tool (MeshLab,
//! Blender, CloudCompare) reads.
//!
//! ## v1 status
//!
//! **Honest implementation** — when the caller supplies a colour /
//! normal sidecar, this entry point writes a hand-rolled extended
//! PLY (header carries the extra properties; vertex rows carry the
//! extra columns) instead of going through the base
//! [`valenx_mesh::format::ply::write_to`]. When both sidecars are
//! empty, the writer falls back to the base PLY (no header
//! overhead, no extra columns). Tri3 connectivity only.

use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

use valenx_mesh::{ElementType, Mesh};

use crate::error::OcctExchangeError;

/// Optional per-vertex annotations.
///
/// `colors` length, when non-empty, must equal `mesh.nodes.len()`.
/// Same constraint on `normals`. Either or both may be empty.
#[derive(Clone, Debug, Default)]
pub struct PlyVertexAnnotations {
    /// Per-vertex 8-bit RGB colour. `Vec::new()` skips the colour
    /// header + columns.
    pub colors: Vec<[u8; 3]>,
    /// Per-vertex 3D normal. `Vec::new()` skips the normal header +
    /// columns.
    pub normals: Vec<[f32; 3]>,
}

/// Write `mesh` to `path` as ASCII PLY, with the colour / normal
/// columns specified by `annotations`.
///
/// # Errors
///
/// - [`OcctExchangeError::BadInput`] if the extension isn't `.ply`,
///   or if the annotation lengths don't match the vertex count.
/// - [`OcctExchangeError::Backend`] for valenx-mesh failures
///   (no-annotation fallback path).
/// - [`OcctExchangeError::Io`] for filesystem failures.
pub fn ply_writer_extended(
    mesh: &Mesh,
    annotations: &PlyVertexAnnotations,
    path: &Path,
) -> Result<(), OcctExchangeError> {
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .map(str::to_ascii_lowercase);
    if ext.as_deref() != Some("ply") {
        return Err(OcctExchangeError::bad_input(
            "path",
            "extension must be .ply",
        ));
    }
    if !annotations.colors.is_empty() && annotations.colors.len() != mesh.nodes.len() {
        return Err(OcctExchangeError::bad_input(
            "annotations.colors",
            format!(
                "length {} does not match vertex count {}",
                annotations.colors.len(),
                mesh.nodes.len(),
            ),
        ));
    }
    if !annotations.normals.is_empty() && annotations.normals.len() != mesh.nodes.len() {
        return Err(OcctExchangeError::bad_input(
            "annotations.normals",
            format!(
                "length {} does not match vertex count {}",
                annotations.normals.len(),
                mesh.nodes.len(),
            ),
        ));
    }
    if annotations.colors.is_empty() && annotations.normals.is_empty() {
        // No annotations → defer to the production writer.
        return valenx_mesh::format::ply::write_path(mesh, path)
            .map_err(|e| OcctExchangeError::Backend(format!("ply::write_path: {e}")));
    }
    let file = File::create(path)?;
    let mut sink = BufWriter::new(file);
    write_extended(mesh, annotations, &mut sink)?;
    sink.flush()?;
    Ok(())
}

fn write_extended<W: Write>(
    mesh: &Mesh,
    ann: &PlyVertexAnnotations,
    sink: &mut W,
) -> std::io::Result<()> {
    let tri_count: usize = mesh
        .element_blocks
        .iter()
        .filter(|b| b.element_type == ElementType::Tri3)
        .map(|b| b.connectivity.len() / 3)
        .sum();
    writeln!(sink, "ply")?;
    writeln!(sink, "format ascii 1.0")?;
    writeln!(sink, "comment generated by valenx-occt-exchange")?;
    writeln!(sink, "element vertex {}", mesh.nodes.len())?;
    writeln!(sink, "property float x")?;
    writeln!(sink, "property float y")?;
    writeln!(sink, "property float z")?;
    if !ann.normals.is_empty() {
        writeln!(sink, "property float nx")?;
        writeln!(sink, "property float ny")?;
        writeln!(sink, "property float nz")?;
    }
    if !ann.colors.is_empty() {
        writeln!(sink, "property uchar red")?;
        writeln!(sink, "property uchar green")?;
        writeln!(sink, "property uchar blue")?;
    }
    writeln!(sink, "element face {tri_count}")?;
    writeln!(sink, "property list uchar int vertex_indices")?;
    writeln!(sink, "end_header")?;
    for (i, n) in mesh.nodes.iter().enumerate() {
        write!(sink, "{} {} {}", fmt_f(n.x), fmt_f(n.y), fmt_f(n.z))?;
        if !ann.normals.is_empty() {
            let nrm = ann.normals[i];
            write!(sink, " {} {} {}", nrm[0], nrm[1], nrm[2])?;
        }
        if !ann.colors.is_empty() {
            let c = ann.colors[i];
            write!(sink, " {} {} {}", c[0], c[1], c[2])?;
        }
        writeln!(sink)?;
    }
    for block in &mesh.element_blocks {
        if block.element_type != ElementType::Tri3 {
            continue;
        }
        for tri in block.connectivity.chunks_exact(3) {
            writeln!(sink, "3 {} {} {}", tri[0], tri[1], tri[2])?;
        }
    }
    Ok(())
}

fn fmt_f(x: f64) -> String {
    let s = format!("{x:.10}");
    let trimmed = s.trim_end_matches('0').trim_end_matches('.');
    if trimmed.is_empty() || trimmed == "-" {
        "0".to_string()
    } else {
        trimmed.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn rejects_wrong_extension() {
        let m = Mesh::new("t");
        let ann = PlyVertexAnnotations::default();
        let err = ply_writer_extended(&m, &ann, &PathBuf::from("a.obj")).unwrap_err();
        assert_eq!(err.code(), "occt_exchange.bad_input");
    }

    #[test]
    fn rejects_color_length_mismatch() {
        let mut m = Mesh::new("t");
        m.nodes = vec![nalgebra::Vector3::zeros(); 3];
        let ann = PlyVertexAnnotations {
            colors: vec![[255, 0, 0]; 2],
            normals: vec![],
        };
        let err = ply_writer_extended(&m, &ann, &PathBuf::from("a.ply")).unwrap_err();
        assert_eq!(err.code(), "occt_exchange.bad_input");
    }
}
