//! Phase 128 — VRML 2.0 (ISO/IEC 14772-1:1997) writer.
//!
//! ## What OCCT does
//!
//! `VrmlAPI_Writer::Write` emits `Shape { IndexedFaceSet }` nodes
//! grouped under `Transform` nodes for the assembly hierarchy.
//! Each face references the global `coord` (3D positions),
//! `coordIndex` (1-based vertex index lists terminated by `-1`),
//! and optional `color` / `colorIndex` for per-face colour.
//!
//! ## v1 status
//!
//! **Honest implementation** for the basic `Shape { IndexedFaceSet
//! { coord Coordinate { point [...] } coordIndex [...] } }` form.
//! Each `Tri3` element block becomes one `Shape` node. Colour /
//! transform hierarchy / texture coords are deferred to Phase
//! 128.5.

use std::path::Path;

use valenx_mesh::{ElementType, Mesh};

use crate::error::OcctExchangeError;

/// Write `mesh` to `path` as VRML 2.0.
///
/// # Errors
///
/// - [`OcctExchangeError::BadInput`] if the extension isn't `.wrl`.
/// - [`OcctExchangeError::Io`] for filesystem failures.
pub fn vrml_writer(mesh: &Mesh, path: &Path) -> Result<(), OcctExchangeError> {
    let ext = path
        .extension()
        .and_then(|s| s.to_str())
        .map(str::to_ascii_lowercase);
    if ext.as_deref() != Some("wrl") {
        return Err(OcctExchangeError::bad_input(
            "path",
            "extension must be .wrl",
        ));
    }
    let mut text = String::from("#VRML V2.0 utf8\n# generated by valenx-occt-exchange\n");
    for block in &mesh.element_blocks {
        if block.element_type != ElementType::Tri3 {
            continue;
        }
        text.push_str("Shape {\n  geometry IndexedFaceSet {\n");
        text.push_str("    coord Coordinate {\n      point [\n");
        for n in &mesh.nodes {
            text.push_str(&format!("        {} {} {},\n", n.x, n.y, n.z));
        }
        text.push_str("      ]\n    }\n    coordIndex [\n");
        for tri in block.connectivity.chunks_exact(3) {
            text.push_str(&format!("      {}, {}, {}, -1,\n", tri[0], tri[1], tri[2]));
        }
        text.push_str("    ]\n  }\n}\n");
    }
    valenx_core::io_caps::atomic_write_str(path, &text)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn rejects_wrong_extension() {
        let m = Mesh::new("t");
        let err = vrml_writer(&m, &PathBuf::from("a.obj")).unwrap_err();
        assert_eq!(err.code(), "occt_exchange.bad_input");
    }
}
