//! Generate Rust consts from `tokens.json`.
//!
//! Runs at compile time. Reads `tokens.json`, validates the shape
//! lightly, and writes `$OUT_DIR/generated.rs` which `lib.rs`
//! `include!`s at module scope.
//!
//! Keep this script small and deterministic. Heavy validation and
//! schema checks belong in `tests/schema.rs`.

use std::io::Read;
use std::{env, fs, path::PathBuf};

use serde_json::Value;

/// Round-23 sweep: build-script-local cap. Even at compile time
/// (`build.rs` runs under cargo, not user input) a poisoned tokens.json
/// would slurp into memory before serde_json saw it; honest token
/// schemas are at most a few dozen KiB. 4 MiB is generous.
const MAX_TOKENS_FILE_BYTES: u64 = 4 * 1024 * 1024;

fn main() {
    println!("cargo:rerun-if-changed=tokens.json");
    println!("cargo:rerun-if-changed=tokens.schema.json");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let tokens_path = PathBuf::from(&manifest_dir).join("tokens.json");

    // Bounded stat + take to refuse a hostile or accidentally-mangled
    // tokens.json that would OOM the build script.
    let meta = fs::metadata(&tokens_path)
        .unwrap_or_else(|e| panic!("failed to stat {}: {e}", tokens_path.display()));
    if meta.len() > MAX_TOKENS_FILE_BYTES {
        panic!(
            "tokens.json at {} is {} bytes; exceeds {MAX_TOKENS_FILE_BYTES}-byte cap",
            tokens_path.display(),
            meta.len()
        );
    }
    let mut buf = Vec::new();
    fs::File::open(&tokens_path)
        .and_then(|f| {
            f.take(MAX_TOKENS_FILE_BYTES.saturating_add(1))
                .read_to_end(&mut buf)
                .map(|_| ())
        })
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", tokens_path.display()));
    if buf.len() as u64 > MAX_TOKENS_FILE_BYTES {
        panic!(
            "tokens.json at {} grew past {MAX_TOKENS_FILE_BYTES}-byte cap mid-read",
            tokens_path.display()
        );
    }
    let raw = String::from_utf8(buf)
        .unwrap_or_else(|e| panic!("tokens.json is not valid UTF-8: {e}"));

    let json: Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("tokens.json is not valid JSON: {e}"));

    let out = env::var_os("OUT_DIR").expect("OUT_DIR");
    let out_path = PathBuf::from(out).join("generated.rs");

    let mut src = String::new();
    src.push_str("// @generated by build.rs — do not edit by hand.\n");
    src.push_str("// Source of truth: crates/valenx-design-tokens/tokens.json\n\n");

    emit_version(&mut src, &json);
    emit_colors(&mut src, &json);
    emit_simple_map_prefixed(
        &mut src,
        "space",
        "Canonical spacing scale (pixels at 1.0 DPI).",
        "S",
        &json["space"],
    );
    emit_simple_map(&mut src, "radius", "Corner radii.", &json["radius"]);
    emit_simple_map(&mut src, "border", "Border widths.", &json["border"]);
    emit_z(&mut src, &json);
    emit_motion(&mut src, &json);
    emit_typography(&mut src, &json);

    fs::write(&out_path, src)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_path.display()));
}

fn emit_version(src: &mut String, json: &Value) {
    let v = json["version"].as_str().unwrap_or("0.0.0");
    src.push_str(&format!(
        "/// Tokens schema version (SemVer).\npub const VERSION: &str = \"{v}\";\n\n"
    ));
}

fn emit_colors(src: &mut String, json: &Value) {
    src.push_str("/// Canonical color tokens, resolved as 0xRRGGBB u32.\npub mod color {\n");

    // surface / text use pure-digit keys — prefix with S / T respectively
    // so the identifiers come out `S1`, `T1` instead of `_1`.
    emit_color_submodule(src, "surface", "S", &json["color"]["surface"]);
    emit_color_submodule(src, "text", "T", &json["color"]["text"]);

    // accent / physics use word keys — sanitize + upper works cleanly.
    emit_color_submodule(src, "accent", "", &json["color"]["accent"]);
    emit_color_submodule(src, "physics", "", &json["color"]["physics"]);

    // Light-theme + high-contrast palettes (the four extra families
    // added in the v0.1.1 token-system extension for the Light /
    // High-Contrast theme variants). All optional in the JSON — the
    // emit_color_submodule helper writes an empty module when the
    // section is missing rather than erroring out.
    emit_color_submodule(src, "light_surface", "S", &json["color"]["light_surface"]);
    emit_color_submodule(src, "light_text", "T", &json["color"]["light_text"]);
    emit_color_submodule(src, "hc_surface", "S", &json["color"]["hc_surface"]);
    emit_color_submodule(src, "hc_text", "T", &json["color"]["hc_text"]);
    emit_color_submodule(src, "hc_accent", "", &json["color"]["hc_accent"]);

    src.push_str("}\n\n");
}

fn emit_color_submodule(src: &mut String, name: &str, prefix: &str, obj: &Value) {
    src.push_str(&format!("    pub mod {name} {{\n"));
    if let Some(map) = obj.as_object() {
        for (k, v) in map {
            let hex = v.as_str().unwrap_or("#000000");
            let rgb = u32::from_str_radix(hex.trim_start_matches('#'), 16).unwrap_or(0);
            let ident = to_const_ident(k, prefix);
            src.push_str(&format!(
                "        /// `{hex}`\n        pub const {ident}: u32 = 0x{rgb:06X};\n"
            ));
        }
    }
    src.push_str("    }\n");
}

fn emit_simple_map(src: &mut String, module: &str, doc: &str, obj: &Value) {
    src.push_str(&format!("/// {doc}\npub mod {module} {{\n"));
    if let Some(map) = obj.as_object() {
        for (k, v) in map {
            let n = v.as_f64().unwrap_or(0.0);
            let ident = to_const_ident(k, "");
            src.push_str(&format!("    pub const {ident}: f32 = {n}_f32;\n"));
        }
    }
    src.push_str("}\n\n");
}

fn emit_simple_map_prefixed(src: &mut String, module: &str, doc: &str, prefix: &str, obj: &Value) {
    src.push_str(&format!("/// {doc}\npub mod {module} {{\n"));
    if let Some(map) = obj.as_object() {
        for (k, v) in map {
            let n = v.as_f64().unwrap_or(0.0);
            let ident = to_const_ident(k, prefix);
            src.push_str(&format!("    pub const {ident}: f32 = {n}_f32;\n"));
        }
    }
    src.push_str("}\n\n");
}

fn emit_z(src: &mut String, json: &Value) {
    src.push_str("/// Z-index tokens.\npub mod z {\n");
    if let Some(obj) = json["z"].as_object() {
        for (k, v) in obj {
            let n = v.as_i64().unwrap_or(0);
            let ident = to_const_ident(k, "");
            src.push_str(&format!("    pub const {ident}: i32 = {n};\n"));
        }
    }
    src.push_str("}\n\n");
}

fn emit_motion(src: &mut String, json: &Value) {
    src.push_str("/// Motion tokens: durations (ms) and easing cubic-bezier control points.\npub mod motion {\n");
    src.push_str("    pub mod duration_ms {\n");
    if let Some(obj) = json["motion"]["duration_ms"].as_object() {
        for (k, v) in obj {
            let ms = v.as_i64().unwrap_or(0);
            let ident = to_const_ident(k, "");
            src.push_str(&format!("        pub const {ident}: u32 = {ms};\n"));
        }
    }
    src.push_str("    }\n");
    src.push_str("    pub mod easing {\n");
    if let Some(obj) = json["motion"]["easing"].as_object() {
        for (k, v) in obj {
            let pts: Vec<f64> = v
                .as_array()
                .map(|a| a.iter().filter_map(|x| x.as_f64()).collect())
                .unwrap_or_default();
            if pts.len() == 4 {
                let ident = to_const_ident(k, "");
                src.push_str(&format!(
                    "        pub const {}: [f32; 4] = [{}_f32, {}_f32, {}_f32, {}_f32];\n",
                    ident, pts[0], pts[1], pts[2], pts[3]
                ));
            }
        }
    }
    src.push_str("    }\n");
    src.push_str("}\n\n");
}

fn emit_typography(src: &mut String, json: &Value) {
    src.push_str("/// Typography tokens.\npub mod typography {\n");

    src.push_str("    /// Font families by role.\n    pub mod family {\n");
    if let Some(obj) = json["type"]["family"].as_object() {
        for (k, v) in obj {
            let fam = v.as_str().unwrap_or("sans-serif");
            let ident = to_const_ident(k, "");
            src.push_str(&format!("        pub const {ident}: &str = \"{fam}\";\n"));
        }
    }
    src.push_str("    }\n");

    src.push_str("    pub mod size {\n");
    if let Some(obj) = json["type"]["size"].as_object() {
        for (k, v) in obj {
            let px = v.as_f64().unwrap_or(0.0);
            // Sizes include keys like "2xl" that start with a digit —
            // prefix with S so they become `S2XL` instead of `_2XL`.
            let ident = to_const_ident(k, "S");
            src.push_str(&format!("        pub const {ident}: f32 = {px}_f32;\n"));
        }
    }
    src.push_str("    }\n");

    src.push_str("    pub mod weight {\n");
    if let Some(obj) = json["type"]["weight"].as_object() {
        for (k, v) in obj {
            let n = v.as_i64().unwrap_or(400);
            let ident = to_const_ident(k, "");
            src.push_str(&format!("        pub const {ident}: u16 = {n};\n"));
        }
    }
    src.push_str("    }\n");

    src.push_str("    pub mod line_height {\n");
    if let Some(obj) = json["type"]["lineHeight"].as_object() {
        for (k, v) in obj {
            let f = v.as_f64().unwrap_or(1.0);
            let ident = to_const_ident(k, "");
            src.push_str(&format!("        pub const {ident}: f32 = {f}_f32;\n"));
        }
    }
    src.push_str("    }\n");

    src.push_str("}\n\n");
}

/// Turn a JSON key into a valid uppercase Rust identifier.
///
/// - Non-alphanumerics become `_`.
/// - If the resulting identifier would start with a digit, the caller
///   supplies a non-empty `prefix` (e.g. `"S"` for spacing, `"T"` for
///   text, `""` for word-keys that don't need one).
/// - Output is uppercased so it matches Rust's SCREAMING_CASE const
///   convention.
fn to_const_ident(key: &str, prefix: &str) -> String {
    let mut body = String::with_capacity(key.len());
    for ch in key.chars() {
        if ch.is_ascii_alphanumeric() {
            body.push(ch);
        } else {
            body.push('_');
        }
    }
    let needs_prefix = body
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(true);

    let combined = if needs_prefix && !prefix.is_empty() {
        format!("{prefix}{body}")
    } else if needs_prefix {
        // No caller-supplied prefix but key starts with a digit —
        // fall back to a leading underscore so the identifier is legal.
        format!("_{body}")
    } else {
        body
    };

    combined.to_uppercase()
}
