//! A tiny, honest writer for OpenFOAM dictionary files.
//!
//! OpenFOAM dict syntax is a C-style block format with a `FoamFile`
//! header declaring `class` and `object` for the parser. Every file
//! in `system/`, `constant/`, and `0/` follows the same shape. This
//! module produces ASCII text that `simpleFoam` et al. accept
//! verbatim; no parsing is attempted in the reverse direction —
//! collecting results is the `collect()` step's job, via VTK.
//!
//! The writer intentionally avoids any template engine: the
//! `FoamFile` header is three lines, the body is a sequence of
//! key/value entries and `name { … }` blocks, and that's the whole
//! surface area. Keeping it first-party (rather than pulling in a
//! templating crate) means `cargo-deny` has less license perimeter
//! to police.

use std::fmt::{self, Write as _};
use std::io;
use std::path::Path;

/// A buffered OpenFOAM dictionary being assembled in memory before
/// being flushed to disk.
pub struct OfDict {
    class: &'static str,
    object: String,
    body: String,
    indent: usize,
}

impl OfDict {
    /// Start a new dict. `class` goes in the `FoamFile` header (e.g.
    /// `"dictionary"`, `"volVectorField"`, `"volScalarField"`).
    /// `object` is the file's logical name (e.g. `"controlDict"`,
    /// `"U"`, `"p"`), which must match the file's basename on disk.
    pub fn new(class: &'static str, object: impl Into<String>) -> Self {
        Self {
            class,
            object: object.into(),
            body: String::new(),
            indent: 0,
        }
    }

    /// Write a single `key value;` line at the current indent level.
    pub fn entry(&mut self, key: &str, value: impl fmt::Display) {
        let pad = "    ".repeat(self.indent);
        // Unwraps are safe: writing into a `String` cannot fail.
        writeln!(&mut self.body, "{pad}{key:<15} {value};").unwrap();
    }

    /// Write a raw line (no trailing `;` added). Use sparingly — this
    /// is the escape hatch for OpenFOAM's richer value types (e.g.
    /// dimensioned vectors written across multiple tokens).
    pub fn raw(&mut self, line: impl fmt::Display) {
        let pad = "    ".repeat(self.indent);
        writeln!(&mut self.body, "{pad}{line}").unwrap();
    }

    /// Write a named block:
    ///
    /// ```text
    /// name
    /// {
    ///     …
    /// }
    /// ```
    pub fn block(&mut self, name: &str, body: impl FnOnce(&mut OfDict)) {
        let pad = "    ".repeat(self.indent);
        writeln!(&mut self.body, "{pad}{name}").unwrap();
        writeln!(&mut self.body, "{pad}{{").unwrap();
        self.indent += 1;
        body(self);
        self.indent -= 1;
        writeln!(&mut self.body, "{pad}}}").unwrap();
    }

    /// Add a blank line to the body — purely cosmetic grouping for
    /// humans reading the generated dicts.
    pub fn blank(&mut self) {
        self.body.push('\n');
    }

    /// Serialize the dict and write it to `path`. The parent directory
    /// is not created; callers are expected to `create_dir_all` first.
    pub fn write_to(&self, path: &Path) -> io::Result<()> {
        let mut out = String::new();
        writeln!(
            &mut out,
            "/*--------------------------------*- C++ -*----------------------------------*\\\n\
             | Generated by valenx-adapter-openfoam. Do not edit by hand. |\n\
             \\*---------------------------------------------------------------------------*/"
        )
        .unwrap();
        writeln!(&mut out, "FoamFile\n{{").unwrap();
        writeln!(&mut out, "    version     2.0;").unwrap();
        writeln!(&mut out, "    format      ascii;").unwrap();
        writeln!(&mut out, "    class       {};", self.class).unwrap();
        writeln!(&mut out, "    object      {};", self.object).unwrap();
        writeln!(&mut out, "}}\n").unwrap();
        out.push_str(&self.body);
        valenx_core::io_caps::atomic_write_str(path, &out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn renders_header_and_entries() {
        let mut d = OfDict::new("dictionary", "controlDict");
        d.entry("application", "simpleFoam");
        d.entry("endTime", 2000);
        d.blank();
        d.block("inlet", |b| {
            b.entry("type", "fixedValue");
            b.raw("value           uniform (50 0 0);");
        });
        let rendered = {
            // Indirect: use write_to + read to avoid leaking a private
            // method. We use a temp dir instead.
            let tmp = std::env::temp_dir().join("valenx-of-dict-test.dict");
            d.write_to(&tmp).unwrap();
            let s = fs::read_to_string(&tmp).unwrap();
            let _ = fs::remove_file(&tmp);
            s
        };
        assert!(rendered.contains("class       dictionary;"));
        assert!(rendered.contains("object      controlDict;"));
        assert!(rendered.contains("application     simpleFoam;"));
        assert!(rendered.contains("inlet\n"));
        assert!(rendered.contains("type            fixedValue;"));
        assert!(rendered.contains("value           uniform (50 0 0);"));
    }
}
