//! Emit a LAMMPS input deck (`in.lammps`) from a typed
//! [`LammpsInput`].

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::{Ensemble, Initialization, LammpsInput, Potential};

pub const DEFAULT_INPUT_FILENAME: &str = "in.lammps";
pub const DUMP_FILENAME: &str = "traj.lammpstrj";
pub const THERMO_FILENAME: &str = "thermo.dat";

pub fn generate(input: &LammpsInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(s, "# Generated by valenx-adapter-lammps — do not edit.\n").unwrap();

    // Basics.
    writeln!(s, "units      {}", input.units.lammps_keyword()).unwrap();
    writeln!(s, "dimension  3").unwrap();
    writeln!(s, "atom_style {}", input.atom_style).unwrap();
    writeln!(
        s,
        "boundary   {} {} {}",
        input.boundary[0].lammps_char(),
        input.boundary[1].lammps_char(),
        input.boundary[2].lammps_char(),
    )
    .unwrap();
    writeln!(s).unwrap();

    // Initialisation.
    write_initialisation(&mut s, &input.initialization);
    writeln!(s).unwrap();

    // Potential.
    write_potential(&mut s, &input.potential);
    writeln!(s).unwrap();

    // Initial velocities (if asked for).
    if let Some(t) = input.initial_temperature {
        writeln!(
            s,
            "velocity   all create {t:.6} 12345 mom yes rot yes dist gaussian"
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    // Ensemble fix.
    match input.ensemble {
        Ensemble::Nve => writeln!(s, "fix        1 all nve").unwrap(),
        Ensemble::NvtNose => {
            let t = input.initial_temperature.unwrap_or(1.0);
            writeln!(s, "fix        1 all nvt temp {t:.6} {t:.6} $(100.0*dt)").unwrap();
        }
        Ensemble::NptParrinelloRahman => {
            let t = input.initial_temperature.unwrap_or(1.0);
            writeln!(
                s,
                "fix        1 all npt temp {t:.6} {t:.6} $(100.0*dt) iso 0.0 0.0 $(1000.0*dt)"
            )
            .unwrap();
        }
    }
    writeln!(s).unwrap();

    // Output.
    writeln!(
        s,
        "thermo        {every}\n\
         thermo_style  custom step temp pe ke etotal press vol\n\
         thermo_modify norm no",
        every = input.thermo_every
    )
    .unwrap();
    writeln!(
        s,
        "dump          1 all custom {every} {file} id type x y z vx vy vz",
        every = input.dump_every,
        file = DUMP_FILENAME
    )
    .unwrap();
    writeln!(s).unwrap();

    // Run.
    writeln!(s, "timestep      {}", input.timestep).unwrap();
    writeln!(s, "run           {}", input.run_steps).unwrap();

    s
}

fn write_initialisation(s: &mut String, init: &Initialization) {
    match init {
        Initialization::LjFccBox {
            density,
            size,
            num_types,
        } => {
            writeln!(s, "# Procedural FCC lattice in a box.").unwrap();
            writeln!(s, "lattice       fcc {density}").unwrap();
            writeln!(
                s,
                "region        box block 0 {} 0 {} 0 {} units lattice",
                size[0], size[1], size[2]
            )
            .unwrap();
            writeln!(s, "create_box    {num_types} box").unwrap();
            writeln!(s, "create_atoms  1 box").unwrap();
            writeln!(s, "mass          1 1.0").unwrap();
        }
        Initialization::ReadData { path } => {
            writeln!(s, "# Atoms from external data file.").unwrap();
            // Forward-slash normalise so Windows paths don't confuse
            // LAMMPS' parser.
            let p = path.to_string_lossy().replace('\\', "/");
            writeln!(s, "read_data     {p}").unwrap();
        }
    }
}

fn write_potential(s: &mut String, pot: &Potential) {
    match pot {
        Potential::LjCut {
            epsilon,
            sigma,
            cutoff,
        } => {
            writeln!(s, "pair_style    lj/cut {cutoff}").unwrap();
            writeln!(s, "pair_coeff    1 1 {epsilon} {sigma} {cutoff}").unwrap();
        }
        Potential::Eam { path, elements } => {
            let p = path.to_string_lossy().replace('\\', "/");
            let element_list = if elements.is_empty() {
                "Fe".to_string()
            } else {
                elements.join(" ")
            };
            writeln!(s, "pair_style    eam/alloy").unwrap();
            writeln!(s, "pair_coeff    * * {p} {element_list}").unwrap();
        }
    }
}

pub fn write_to_file(input: &LammpsInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{
        BoundaryCondition, Ensemble, Initialization, LammpsInput, Potential, Units,
    };

    fn lj_input() -> LammpsInput {
        LammpsInput {
            units: Units::Lj,
            atom_style: "atomic".into(),
            boundary: [
                BoundaryCondition::P,
                BoundaryCondition::P,
                BoundaryCondition::P,
            ],
            initialization: Initialization::LjFccBox {
                density: 0.8442,
                size: [10.0, 10.0, 10.0],
                num_types: 1,
            },
            potential: Potential::LjCut {
                epsilon: 1.0,
                sigma: 1.0,
                cutoff: 2.5,
            },
            ensemble: Ensemble::Nve,
            run_steps: 2000,
            timestep: 0.005,
            initial_temperature: Some(1.0),
            thermo_every: 50,
            dump_every: 100,
        }
    }

    #[test]
    fn deck_has_expected_lines() {
        let deck = generate(&lj_input());
        assert!(deck.contains("units      lj"));
        assert!(deck.contains("atom_style atomic"));
        assert!(deck.contains("boundary   p p p"));
        assert!(deck.contains("lattice       fcc 0.8442"));
        assert!(deck.contains("region        box block 0 10 0 10 0 10"));
        assert!(deck.contains("create_box    1 box"));
        assert!(deck.contains("pair_style    lj/cut 2.5"));
        assert!(deck.contains("pair_coeff    1 1 1 1 2.5"));
        assert!(deck.contains("velocity   all create 1.000000"));
        assert!(deck.contains("fix        1 all nve"));
        assert!(deck.contains("thermo        50"));
        assert!(deck.contains("dump          1 all custom 100 traj.lammpstrj"));
        assert!(deck.contains("timestep      0.005"));
        assert!(deck.contains("run           2000"));
    }

    #[test]
    fn nvt_ensemble_emits_nvt_fix() {
        let mut input = lj_input();
        input.ensemble = Ensemble::NvtNose;
        let deck = generate(&input);
        assert!(deck.contains("fix        1 all nvt"));
    }

    #[test]
    fn eam_potential_uses_alloy_style() {
        let mut input = lj_input();
        input.potential = Potential::Eam {
            path: std::path::PathBuf::from("Cu_mishin.eam.alloy"),
            elements: vec!["Cu".into()],
        };
        let deck = generate(&input);
        assert!(deck.contains("pair_style    eam/alloy"));
        assert!(deck.contains("pair_coeff    * * Cu_mishin.eam.alloy Cu"));
    }

    #[test]
    fn read_data_init_uses_read_data() {
        let mut input = lj_input();
        input.initialization = Initialization::ReadData {
            path: std::path::PathBuf::from("system.data"),
        };
        let deck = generate(&input);
        assert!(deck.contains("read_data     system.data"));
    }
}
