//! FemAnalysis — the central pre-processor record.

use std::path::Path;

use thiserror::Error;

use valenx_cad::Solid;

use crate::constraints::FemConstraint;
use crate::loads::FemLoad;
use crate::material::FemMaterial;
use crate::mesh_params::FemMeshParams;
use crate::solver::FemSolverChoice;

/// Errors from the FEM pre-processor.
#[derive(Debug, Error)]
pub enum FemAnalysisError {
    /// Filesystem failure (writing the input deck).
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    /// Caller asked for a feature this version doesn't support.
    #[error("unsupported: {0}")]
    Unsupported(String),
    /// Source solid is empty / has no faces.
    #[error("empty solid")]
    EmptySolid,
}

/// One FEM analysis case — source geometry + material + BCs + mesh
/// settings + chosen solver.
#[derive(Clone, Debug)]
pub struct FemAnalysis {
    /// Source [`Solid`] (any variant — mesh or BRep).
    pub source_solid: Solid,
    /// Material assignment.
    pub material: FemMaterial,
    /// Boundary conditions.
    pub constraints: Vec<FemConstraint>,
    /// Applied loads.
    pub loads: Vec<FemLoad>,
    /// Mesh-generation parameters.
    pub mesh_params: FemMeshParams,
    /// Which solver to dispatch to.
    pub solver_choice: FemSolverChoice,
}

impl FemAnalysis {
    /// Build a fresh analysis for `solid` with sensible defaults.
    pub fn new(solid: Solid) -> Self {
        Self {
            source_solid: solid,
            material: FemMaterial::default(),
            constraints: Vec::new(),
            loads: Vec::new(),
            mesh_params: FemMeshParams::default(),
            solver_choice: FemSolverChoice::default(),
        }
    }

    /// Tessellate the source solid for the solver. v1 returns a
    /// surface mesh — the meshing adapter (gmsh / Netgen) is
    /// responsible for the volumetric mesh.
    ///
    /// # Errors
    ///
    /// - [`FemAnalysisError::EmptySolid`] when the source solid
    ///   tessellates to zero triangles.
    pub fn tessellate_for_solver(&self) -> Result<valenx_mesh::Mesh, FemAnalysisError> {
        let mesh = match &self.source_solid {
            Solid::Mesh(m) => m.clone(),
            Solid::Brep(_) => {
                valenx_cad::solid_to_mesh(&self.source_solid, self.mesh_params.element_size)
                    .map_err(|e| FemAnalysisError::Unsupported(format!("tessellate: {e}")))?
            }
        };
        if mesh.nodes.is_empty() {
            return Err(FemAnalysisError::EmptySolid);
        }
        Ok(mesh)
    }

    /// Write a solver-specific input deck to `path`.
    ///
    /// v1 emits a minimal CalculiX `.inp` plus stub Elmer `.sif` and
    /// Code_Aster `.comm` files. The downstream adapter's existing
    /// writers fill in the high-fidelity details — this stub gets the
    /// pre-processor's record into the right file shape and ensures
    /// the round-trip path is end-to-end before the solver call.
    ///
    /// # Errors
    ///
    /// - [`FemAnalysisError::Io`] for write failures.
    pub fn write_input_file(&self, path: &Path) -> Result<(), FemAnalysisError> {
        let text = match self.solver_choice {
            FemSolverChoice::CalculiX => self.emit_calculix_input(),
            FemSolverChoice::Elmer => self.emit_elmer_input(),
            FemSolverChoice::CodeAster => self.emit_codeaster_input(),
        };
        valenx_core::io_caps::atomic_write_str(path, &text)?;
        Ok(())
    }

    /// Adapter ID to invoke. Surfaced separately so the desktop shell
    /// can chain `write_input_file -> launch(adapter_id) -> collect`.
    pub fn launch_adapter_id(&self) -> &'static str {
        self.solver_choice.adapter_id()
    }

    fn emit_calculix_input(&self) -> String {
        let mut out = String::new();
        out.push_str("** Generated by valenx-fem (Phase 24)\n");
        out.push_str(&format!("** Solver: {}\n", self.solver_choice.label()));
        out.push_str(&format!("** Material: {}\n", self.material.name));
        out.push_str(&format!(
            "** Element order: {} ({} CCX)\n",
            element_label(self.mesh_params.element_type),
            self.mesh_params.element_type.ccx_code(),
        ));
        out.push_str("*HEADING\nvalenx FEM analysis\n");
        out.push_str(&format!("*MATERIAL, NAME={}\n", self.material.name));
        out.push_str("*ELASTIC\n");
        out.push_str(&format!(
            "{}, {}\n",
            self.material.youngs_modulus, self.material.poisson_ratio
        ));
        out.push_str("*DENSITY\n");
        out.push_str(&format!("{}\n", self.material.density));
        for (i, c) in self.constraints.iter().enumerate() {
            out.push_str(&format!("** Constraint {i}: {}\n", c.kind_label()));
            match c {
                FemConstraint::Fixed { face_id } => {
                    out.push_str(&format!("*BOUNDARY\nNSET_face_{face_id}, 1, 6\n",));
                }
                FemConstraint::Displacement { face_id, value } => {
                    for (dof, v) in value.iter().enumerate() {
                        out.push_str(&format!(
                            "*BOUNDARY\nNSET_face_{face_id}, {}, {}, {}\n",
                            dof + 1,
                            dof + 1,
                            v,
                        ));
                    }
                }
                _ => {}
            }
        }
        for (i, l) in self.loads.iter().enumerate() {
            out.push_str(&format!("** Load {i}: {}\n", l.kind_label()));
            match l {
                FemLoad::PointForce { vertex, vector } => {
                    for (dof, v) in vector.iter().enumerate() {
                        out.push_str(&format!("*CLOAD\n{vertex}, {}, {}\n", dof + 1, v,));
                    }
                }
                FemLoad::PressureForce { face, magnitude } => {
                    out.push_str(&format!("*DLOAD\nELSET_face_{face}, P, {magnitude}\n",));
                }
                _ => {}
            }
        }
        out.push_str("*STEP\n*STATIC\n*END STEP\n");
        out
    }

    fn emit_elmer_input(&self) -> String {
        let mut out = String::new();
        out.push_str("! Generated by valenx-fem (Phase 24) — Elmer .sif\n");
        out.push_str("Header\n  Mesh DB \".\" \"mesh\"\nEnd\n\n");
        out.push_str("Simulation\n  Coordinate System = Cartesian\n  Simulation Type = Steady State\nEnd\n\n");
        out.push_str(&format!(
            "Material 1\n  Name = \"{}\"\n  Density = {}\n  Youngs modulus = {}\n  Poisson ratio = {}\nEnd\n\n",
            self.material.name,
            self.material.density,
            self.material.youngs_modulus,
            self.material.poisson_ratio,
        ));
        out.push_str("Solver 1\n  Equation = \"Elasticity\"\n  Procedure = \"StressSolve\" \"StressSolver\"\nEnd\n");
        out
    }

    fn emit_codeaster_input(&self) -> String {
        let mut out = String::new();
        out.push_str("# Generated by valenx-fem (Phase 24) — Code_Aster .comm\n");
        out.push_str("DEBUT()\n");
        out.push_str(&format!(
            "MAT = DEFI_MATERIAU(ELAS=_F(E={}, NU={}, RHO={}))\n",
            self.material.youngs_modulus, self.material.poisson_ratio, self.material.density,
        ));
        out.push_str("FIN()\n");
        out
    }
}

fn element_label(o: crate::mesh_params::ElementOrder) -> &'static str {
    match o {
        crate::mesh_params::ElementOrder::Tet4 => "Tet4",
        crate::mesh_params::ElementOrder::Tet10 => "Tet10",
        crate::mesh_params::ElementOrder::Hex8 => "Hex8",
        crate::mesh_params::ElementOrder::Hex20 => "Hex20",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh_params::ElementOrder;
    use valenx_cad::Solid;
    use valenx_mesh::Mesh;

    #[test]
    fn new_analysis_uses_defaults() {
        let m = Mesh::new("test");
        let a = FemAnalysis::new(Solid::from_mesh(m));
        assert_eq!(a.material.name, "Steel_AISI_1045");
        assert_eq!(a.solver_choice, FemSolverChoice::CalculiX);
        assert_eq!(a.mesh_params.element_type, ElementOrder::Tet10);
    }

    #[test]
    fn calculix_input_includes_material_block() {
        let m = Mesh::new("t");
        let a = FemAnalysis::new(Solid::from_mesh(m));
        let inp = a.emit_calculix_input();
        assert!(inp.contains("*MATERIAL, NAME=Steel_AISI_1045"));
        assert!(inp.contains("*ELASTIC"));
        assert!(inp.contains("*DENSITY"));
        assert!(inp.contains("*STEP"));
    }

    #[test]
    fn elmer_input_uses_sif_keywords() {
        let m = Mesh::new("t");
        let mut a = FemAnalysis::new(Solid::from_mesh(m));
        a.solver_choice = FemSolverChoice::Elmer;
        let sif = a.emit_elmer_input();
        assert!(sif.contains("Header"));
        assert!(sif.contains("Simulation"));
        assert!(sif.contains("Material 1"));
        assert!(sif.contains("Solver 1"));
    }

    #[test]
    fn codeaster_input_uses_comm_keywords() {
        let m = Mesh::new("t");
        let mut a = FemAnalysis::new(Solid::from_mesh(m));
        a.solver_choice = FemSolverChoice::CodeAster;
        let comm = a.emit_codeaster_input();
        assert!(comm.contains("DEBUT"));
        assert!(comm.contains("DEFI_MATERIAU"));
        assert!(comm.contains("FIN"));
    }

    #[test]
    fn launch_adapter_id_matches_choice() {
        let m = Mesh::new("t");
        let mut a = FemAnalysis::new(Solid::from_mesh(m));
        assert_eq!(a.launch_adapter_id(), "calculix");
        a.solver_choice = FemSolverChoice::Elmer;
        assert_eq!(a.launch_adapter_id(), "elmer");
        a.solver_choice = FemSolverChoice::CodeAster;
        assert_eq!(a.launch_adapter_id(), "code-aster");
    }

    #[test]
    fn write_input_file_writes_bytes() {
        let m = valenx_mesh::Mesh::new("t");
        let a = FemAnalysis::new(Solid::from_mesh(m));
        let tmp = std::env::temp_dir().join("valenx_fem_inp_test.inp");
        let _ = std::fs::remove_file(&tmp);
        a.write_input_file(&tmp).unwrap();
        let txt = std::fs::read_to_string(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert!(txt.contains("*MATERIAL"));
    }

    #[test]
    fn tessellate_empty_mesh_errors() {
        let m = valenx_mesh::Mesh::new("empty");
        let a = FemAnalysis::new(Solid::from_mesh(m));
        let err = a.tessellate_for_solver().unwrap_err();
        assert!(matches!(err, FemAnalysisError::EmptySolid));
    }

    #[test]
    fn constraints_with_displacement_emit_per_dof_lines() {
        let m = valenx_mesh::Mesh::new("t");
        let mut a = FemAnalysis::new(Solid::from_mesh(m));
        a.constraints.push(FemConstraint::Displacement {
            face_id: 3,
            value: [0.001, 0.0, 0.0],
        });
        let inp = a.emit_calculix_input();
        assert!(inp.contains("NSET_face_3, 1, 1, 0.001"));
        assert!(inp.contains("NSET_face_3, 2, 2, 0"));
    }

    #[test]
    fn pressure_load_emits_dload() {
        let m = valenx_mesh::Mesh::new("t");
        let mut a = FemAnalysis::new(Solid::from_mesh(m));
        a.loads.push(FemLoad::PressureForce {
            face: 5,
            magnitude: 1e6,
        });
        let inp = a.emit_calculix_input();
        assert!(inp.contains("*DLOAD"));
        assert!(inp.contains("ELSET_face_5"));
    }
}
