//! Lock-in test: the case.toml shape that `valenx-init --template
//! elmer-heat` writes must parse cleanly through the Elmer adapter's
//! `case_input` module.
//!
//! Mirrors the LAMMPS template-parse test. Drift between the
//! template body and this duplicate surfaces as a parse failure or
//! divergent text in code review. Pre-fix, the template wrote
//! `kind = "temperature"` / `value = ...` for boundaries while
//! `parse_boundary` expected `temperature = <value>` directly —
//! every scaffolded heat case silently dropped its Dirichlet BCs.
//! This test would have caught it.

use valenx_adapter_elmer::case_input::{BoundaryCondition, ElmerInput, Equation};
use valenx_core::CaseDef;

const TEMPLATE_CASE_TOML: &str = r#"# Generated by `valenx-init`. Edit freely.
[case]
format  = "1.0"
name    = "heat-cube"
physics = "fea"
solver  = "elmer.heat"
mesh    = "(none)"

# Steady-state heat conduction with two opposing faces pinned to
# fixed temperatures. The body settles into a linear gradient.
# Generate the mesh with gmsh / Netgen first and point `mesh_dir`
# at the produced `.unv` / canonical mesh.
[heat]
mesh_dir = "mesh"

[heat.material]
name              = "aluminium"
density           = 2700.0
heat_capacity     = 900.0
heat_conductivity = 237.0

[[heat.boundaries]]
name        = "hot_face"
target      = 1
temperature = 373.15

[[heat.boundaries]]
name        = "cold_face"
target      = 2
temperature = 273.15

[heat.simulation]
max_output_level            = 5
steady_state_max_iterations = 50
convergence_tolerance       = 1.0e-6
"#;

#[test]
fn elmer_heat_template_case_toml_parses_through_adapter() {
    let case_def: CaseDef =
        toml::from_str(TEMPLATE_CASE_TOML).expect("template case.toml is valid TOML");
    let input = ElmerInput::from_case_def(&case_def).expect("parses through Elmer adapter");

    assert!(matches!(input.equation, Equation::HeatEquation));
    assert_eq!(input.material.name, "aluminium");
    assert_eq!(input.boundaries.len(), 2);
    let mut hot_seen = false;
    let mut cold_seen = false;
    for b in &input.boundaries {
        if let BoundaryCondition::Temperature { name, value, .. } = b {
            if name == "hot_face" {
                hot_seen = true;
                assert!((value - 373.15).abs() < 1e-6);
            } else if name == "cold_face" {
                cold_seen = true;
                assert!((value - 273.15).abs() < 1e-6);
            }
        }
    }
    assert!(hot_seen, "hot_face not found in {:?}", input.boundaries);
    assert!(cold_seen, "cold_face not found in {:?}", input.boundaries);
}
