//! An artifact is a raw file an adapter left on disk alongside the
//! canonical results — solver log, raw CSV, native-format mesh dump,
//! etc. `Results.artifacts` is a list of these so power users can
//! reach the ground truth without groping through the filesystem.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::provenance::Sha256Hex;

/// Broad category of raw artifact, for UI filtering.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ArtifactKind {
    /// Solver stdout / stderr capture.
    Log,
    /// Tabular data (CSV, TSV).
    Tabular,
    /// Binary mesh or field in the solver's native format.
    Native,
    /// VTK / CGNS / HDF5 result file.
    VizData,
    /// Plot images generated by the solver directly.
    Image,
    /// Anything else.
    Other,
}

/// A file in the results directory that's not part of the canonical
/// `Field` / `ScalarRecord` set but is kept for reference.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Artifact {
    pub path: PathBuf,
    pub kind: ArtifactKind,
    /// Optional SHA-256 of the file contents — useful for integrity
    /// checks across a result's lifetime.
    pub checksum: Option<Sha256Hex>,
    /// Short human label for the UI ("solver log", "residual history").
    pub label: String,
}
