//! Generate a deterministic Python script that drives Cantera for
//! the selected analysis. Same pattern as the FreeCAD adapter:
//! write a small, readable `.py` file and invoke it via
//! `python valenx_cantera.py`.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::ChemistryInput;

pub const SCRIPT_FILENAME: &str = "valenx_cantera.py";
pub const SUMMARY_FILENAME: &str = "summary.json";

/// Emit the script as a string.
pub fn generate(input: &ChemistryInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "# Generated by valenx-adapter-cantera — do not edit by hand.\n\
         # Re-running `prepare()` overwrites this file.\n"
    )
    .unwrap();

    writeln!(s, "import json, math\nimport cantera as ct\n").unwrap();

    // Solution / mechanism.
    writeln!(s, "gas = ct.Solution({})", input.mechanism.as_python_arg()).unwrap();

    // Initial state — TPX in Cantera is "temperature, pressure, mole-fraction".
    //
    // Round-19 H2 / L3: composition is user-controlled and previously
    // only had `"` escaped via `.replace('"', "\\\"")`, which missed
    // `\`, `\n`, `\r`, and control bytes — a composition string like
    // `"X:1\");\nimport os\nx = ct.Solution(\""` would close the literal
    // and inject statement-level Python. Route through
    // [`python_str_repr`] so every Python-source escape gets handled
    // consistently with the mechanism + parameter-set sites.
    let t = input.initial.temperature_k;
    let p = input.initial.pressure_pa;
    let composition = valenx_core::adapter_helpers::python_str_repr(&input.initial.composition);
    writeln!(s, "gas.TPX = {t:.6}, {p:.6}, \"{composition}\"").unwrap();

    // Record initial state for the summary.
    writeln!(
        s,
        "initial_state = dict(T=gas.T, P=gas.P, H=gas.enthalpy_mass, \
         S=gas.entropy_mass, rho=gas.density_mass)\n"
    )
    .unwrap();

    if input.analysis.is_reactor() {
        emit_reactor_network(&mut s, input);
    } else {
        emit_equilibrium(&mut s, input);
    }

    s
}

/// Emit the equilibrium-mode script body. The original Phase 4 path:
/// gas.equilibrate(basis) + species filter + summary write.
fn emit_equilibrium(s: &mut String, input: &ChemistryInput) {
    writeln!(
        s,
        "gas.equilibrate(\"{}\")",
        input.analysis.equilibrate_basis()
    )
    .unwrap();
    writeln!(
        s,
        "THRESHOLD = 1.0e-8\n\
         mole_fractions = {{}}\n\
         for i, sp in enumerate(gas.species_names):\n    \
             x = gas.X[i]\n    \
             if x > THRESHOLD:\n        \
                 mole_fractions[sp] = float(x)\n"
    )
    .unwrap();
    writeln!(
        s,
        "summary = {{\n    \
             \"valenx_adapter\": \"cantera\",\n    \
             \"analysis\": \"{basis}\",\n    \
             \"mechanism\": {mechanism},\n    \
             \"initial\": initial_state,\n    \
             \"final\": dict(T=gas.T, P=gas.P, H=gas.enthalpy_mass, \
         S=gas.entropy_mass, rho=gas.density_mass),\n    \
             \"mole_fractions\": mole_fractions,\n    \
             \"mean_molecular_weight\": float(gas.mean_molecular_weight),\n    \
             \"species_count_kept\": len(mole_fractions),\n    \
             \"species_count_total\": gas.n_species,\n\
         }}",
        basis = input.analysis.equilibrate_basis(),
        mechanism = input.mechanism.as_python_arg(),
    )
    .unwrap();
    writeln!(
        s,
        "\nwith open(\"{SUMMARY_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             json.dump(summary, f, indent=2)\n\
         print(f\"[valenx] equilibrium reached — final T={{gas.T:.2f}} K, \
         {{summary['species_count_kept']}} species kept\")"
    )
    .unwrap();
}

/// Emit the reactor-network mode script body. Cantera's IdealGas{,
/// ConstPressure}Reactor + ReactorNet handle the stiff ODE
/// integration; we sample the trajectory at `n_samples` evenly-
/// spaced times and persist the time-history as JSON.
fn emit_reactor_network(s: &mut String, input: &ChemistryInput) {
    let reactor_class = input
        .analysis
        .reactor_class()
        .expect("is_reactor implies reactor_class is Some");
    let cfg = input
        .reactor
        .as_ref()
        .expect("case_input::from_case_def enforces reactor.is_some when is_reactor()");
    let analysis_label = match input.analysis {
        crate::case_input::Analysis::BatchReactorConstP => "batch-reactor-const-p",
        crate::case_input::Analysis::BatchReactorConstV => "batch-reactor-const-v",
        _ => "batch-reactor",
    };

    writeln!(s, "reactor = ct.{reactor_class}(gas)").unwrap();
    writeln!(s, "network = ct.ReactorNet([reactor])").unwrap();
    writeln!(
        s,
        "end_time = {end:.10e}\n\
         n_samples = {n}\n\
         dt = end_time / (n_samples - 1)",
        end = cfg.end_time_s,
        n = cfg.n_samples
    )
    .unwrap();

    writeln!(
        s,
        "history = []\n\
         t_ignition = None\n\
         T0 = reactor.T\n\
         for k in range(n_samples):\n    \
             target = k * dt\n    \
             if k == 0:\n        \
                 # Sample the initial state without advancing\n        \
                 t = network.time\n    \
             else:\n        \
                 network.advance(target)\n        \
                 t = network.time\n    \
             # Detect ignition: first sample where T > T0 + 400 K.\n    \
             # Common convention for ignition-delay studies; the user\n    \
             # can re-derive a stricter criterion from the time-history.\n    \
             if t_ignition is None and reactor.T > T0 + 400.0:\n        \
                 t_ignition = t\n    \
             history.append(dict(\n        \
                 t=float(t),\n        \
                 T=float(reactor.T),\n        \
                 P=float(reactor.thermo.P),\n        \
                 H=float(reactor.thermo.enthalpy_mass),\n        \
                 rho=float(reactor.thermo.density_mass),\n    \
             ))"
    )
    .unwrap();

    writeln!(
        s,
        "\nTHRESHOLD = 1.0e-8\n\
         mole_fractions_final = {{}}\n\
         for i, sp in enumerate(reactor.thermo.species_names):\n    \
             x = reactor.thermo.X[i]\n    \
             if x > THRESHOLD:\n        \
                 mole_fractions_final[sp] = float(x)\n"
    )
    .unwrap();

    writeln!(
        s,
        "summary = {{\n    \
             \"valenx_adapter\": \"cantera\",\n    \
             \"analysis\": \"{analysis}\",\n    \
             \"mechanism\": {mechanism},\n    \
             \"reactor_class\": \"{reactor_class}\",\n    \
             \"initial\": initial_state,\n    \
             \"final\": dict(T=float(reactor.T), P=float(reactor.thermo.P), \
         H=float(reactor.thermo.enthalpy_mass), \
         S=float(reactor.thermo.entropy_mass), \
         rho=float(reactor.thermo.density_mass)),\n    \
             \"end_time_s\": end_time,\n    \
             \"n_samples\": n_samples,\n    \
             \"ignition_delay_s\": t_ignition,\n    \
             \"mole_fractions\": mole_fractions_final,\n    \
             \"mean_molecular_weight_final\": float(reactor.thermo.mean_molecular_weight),\n    \
             \"species_count_kept\": len(mole_fractions_final),\n    \
             \"species_count_total\": reactor.thermo.n_species,\n    \
             \"time_history\": history,\n\
         }}",
        analysis = analysis_label,
        mechanism = input.mechanism.as_python_arg(),
        reactor_class = reactor_class,
    )
    .unwrap();

    writeln!(
        s,
        "\nwith open(\"{SUMMARY_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             json.dump(summary, f, indent=2)\n\
         msg = f\"[valenx] reactor network integrated to t={{end_time:.3e}} s — \
         final T={{reactor.T:.2f}} K\"\n\
         if t_ignition is not None:\n    \
             msg += f\" (ignition at t={{t_ignition:.3e}} s)\"\n\
         print(msg)"
    )
    .unwrap();
}

pub fn write_to_file(input: &ChemistryInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{Analysis, Mechanism, ThermoState};

    fn tp_input() -> ChemistryInput {
        ChemistryInput {
            mechanism: Mechanism::Bundled("gri30.yaml".into()),
            analysis: Analysis::EquilibriumTP,
            initial: ThermoState {
                temperature_k: 1800.0,
                pressure_pa: 101325.0,
                composition: "H2:2, O2:1, N2:3.76".into(),
            },
            reactor: None,
        }
    }

    fn reactor_input() -> ChemistryInput {
        ChemistryInput {
            mechanism: Mechanism::Bundled("gri30.yaml".into()),
            analysis: Analysis::BatchReactorConstP,
            initial: ThermoState {
                temperature_k: 1200.0,
                pressure_pa: 101325.0,
                composition: "CH4:1, O2:2, N2:7.52".into(),
            },
            reactor: Some(crate::case_input::ReactorNetwork {
                end_time_s: 0.05,
                n_samples: 50,
            }),
        }
    }

    #[test]
    fn script_references_mechanism_and_state() {
        let s = generate(&tp_input());
        assert!(s.contains("ct.Solution(\"gri30.yaml\")"));
        assert!(s.contains("gas.TPX = 1800.000000, 101325.000000"));
        assert!(s.contains("H2:2, O2:1, N2:3.76"));
        assert!(s.contains("gas.equilibrate(\"TP\")"));
        assert!(s.contains("summary.json"));
        assert!(s.contains("mole_fractions"));
    }

    #[test]
    fn external_mechanism_path_is_quoted_and_slashed() {
        let mut input = tp_input();
        input.mechanism = Mechanism::External(std::path::PathBuf::from("mech\\dir\\custom.yaml"));
        let s = generate(&input);
        assert!(s.contains("ct.Solution(\"mech/dir/custom.yaml\")"));
    }

    #[test]
    fn hp_analysis_emits_hp_basis() {
        let mut input = tp_input();
        input.analysis = Analysis::EquilibriumHP;
        let s = generate(&input);
        assert!(s.contains("gas.equilibrate(\"HP\")"));
    }

    #[test]
    fn script_includes_mole_fraction_threshold() {
        let s = generate(&tp_input());
        assert!(s.contains("THRESHOLD = 1.0e-8"));
    }

    // -----------------------------------------------------------------
    // Reactor-network mode
    // -----------------------------------------------------------------

    #[test]
    fn reactor_script_does_not_call_equilibrate() {
        // The reactor branch must integrate over time, NOT call
        // gas.equilibrate(...) — the latter would skip the kinetics
        // and short-circuit ignition-delay analysis.
        let s = generate(&reactor_input());
        assert!(!s.contains("gas.equilibrate("), "got:\n{s}");
    }

    #[test]
    fn reactor_script_constructs_idealgas_const_pressure_reactor() {
        let s = generate(&reactor_input());
        assert!(
            s.contains("ct.IdealGasConstPressureReactor(gas)"),
            "got:\n{s}"
        );
        assert!(s.contains("ct.ReactorNet([reactor])"));
    }

    #[test]
    fn reactor_script_uses_const_volume_class_for_constv_variant() {
        let mut input = reactor_input();
        input.analysis = Analysis::BatchReactorConstV;
        let s = generate(&input);
        assert!(s.contains("ct.IdealGasReactor(gas)"), "got:\n{s}");
        assert!(!s.contains("ct.IdealGasConstPressureReactor"));
    }

    #[test]
    fn reactor_script_emits_end_time_and_sample_count() {
        let s = generate(&reactor_input());
        // 0.05 in scientific notation; tolerate either '5.0e-2' or
        // '5.0000000000e-2' style.
        assert!(s.contains("end_time = 5.0"), "got:\n{s}");
        assert!(s.contains("n_samples = 50"));
    }

    #[test]
    fn reactor_script_includes_ignition_delay_detection() {
        // The reactor branch detects ignition as the first sample
        // where T exceeds T0 + 400 K — the standard convention for
        // ignition-delay studies.
        let s = generate(&reactor_input());
        assert!(s.contains("t_ignition"), "got:\n{s}");
        assert!(s.contains("T0 + 400.0"));
        assert!(s.contains("\"ignition_delay_s\": t_ignition"));
    }

    #[test]
    fn reactor_script_records_time_history_in_summary() {
        let s = generate(&reactor_input());
        assert!(s.contains("\"time_history\": history"), "got:\n{s}");
        // Each history entry must record at least t / T / P / rho so
        // downstream plotting can reconstruct the trajectory without
        // re-running the case.
        assert!(s.contains("t=float(t),"));
        assert!(s.contains("T=float(reactor.T),"));
        assert!(s.contains("P=float(reactor.thermo.P),"));
        assert!(s.contains("rho=float(reactor.thermo.density_mass),"));
    }

    #[test]
    fn reactor_script_print_message_mentions_reactor_network() {
        let s = generate(&reactor_input());
        assert!(
            s.contains("[valenx] reactor network integrated"),
            "got:\n{s}"
        );
    }

    // -----------------------------------------------------------------
    // Round-19 H2: Python-injection guards (composition + mechanism).
    // Pre-fix the composition site used `.replace('"', "\\\"")` which
    // missed `\`, `\n`, `\r`, and control bytes — a `composition`
    // field with a closing quote + newline + arbitrary statement
    // would break out of the literal and turn the next line into
    // Python code the case-author controls.
    // -----------------------------------------------------------------

    /// Round-19 H2 RED→GREEN: a hostile `composition` field MUST NOT
    /// escape the Python literal it's embedded in. We exercise the
    /// canonical payload: close the literal with `");`, emit an
    /// `import os` on the next line, then re-open a stub literal so
    /// the trailing `gas.TPX = ...` line stays syntactically valid.
    #[test]
    fn composition_injection_payload_is_escaped() {
        let mut input = tp_input();
        input.initial.composition = "X:1\");\nimport os\ngas.TPX = (0.0, 0.0, \"".into();
        let s = generate(&input);
        // The raw injection shape MUST NOT survive.
        assert!(
            !s.contains("\");\nimport os"),
            "raw `\");\\nimport os` composition injection survived"
        );
        assert!(
            !s.contains("\nimport os\n"),
            "raw `\\nimport os\\n` survived through escape: {s}"
        );
        // The escaped form has `\\\"` (escaped quote) + `\\n` for the
        // newline — both must be in the script.
        assert!(s.contains("\\\""), "expected escaped quote in script");
        assert!(s.contains("\\n"), "expected escaped newline in script");
    }

    /// Round-19 H2: the `mechanism = "..."` (Bundled variant) field
    /// is also user-controlled and routes through
    /// `Mechanism::as_python_arg`. Pre-fix it was emitted as
    /// `format!("\"{name}\"")` with no escaping at all. A hostile
    /// `mechanism = "gri30.yaml\");\nimport os\nx = ct.Solution(\""`
    /// would close the `ct.Solution(...)` literal and inject Python
    /// statements before `gas.TPX = ...`.
    #[test]
    fn bundled_mechanism_injection_payload_is_escaped() {
        let mut input = tp_input();
        input.mechanism = crate::case_input::Mechanism::Bundled(
            "gri30.yaml\");\nimport os\nx = ct.Solution(\"".into(),
        );
        let s = generate(&input);
        assert!(
            !s.contains("\");\nimport os"),
            "raw `\");\\nimport os` mechanism injection survived"
        );
        // Sanity: the script still starts with the import preamble.
        assert!(s.contains("import json"));
        assert!(s.contains("ct.Solution("));
    }
}
