//! Python export — turn a [`crate::Macro`] into a self-contained
//! Python script that calls the `valenx` module shipped by Phase 11
//! (`valenx-py`).
//!
//! The script is written to be readable, with one Python statement per
//! action and a small header. The dispatch shape mirrors the
//! Rust-side [`crate::dispatcher::MacroDispatcher`] trait — every
//! action lands as a method call on `app`.

use crate::action::{EntityKind, MacroAction};
use crate::Macro;

/// Render a macro as a Python script.
///
/// User-controlled fields (`name`, `description`, and `Step.label`) are
/// emitted as Python comments. Without sanitisation, a newline embedded
/// in any of these would break out of the comment context and let an
/// attacker inject executable Python — every line that follows the `\n`
/// would land at column 0 of the generated script, ready to run. We
/// therefore replace `\n`, `\r`, and the literal three-quote escape
/// in those fields before they hit the format string.
pub fn to_python(m: &Macro) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by valenx-macro\n");
    out.push_str(&format!("# Macro: {}\n", sanitise_comment(&m.name)));
    if !m.description.is_empty() {
        for line in m.description.lines() {
            out.push_str(&format!("# {}\n", sanitise_comment(line)));
        }
    }
    out.push('\n');
    out.push_str("import valenx\n\n");
    out.push_str("app = valenx.App.new()\n");
    for action in &m.actions {
        out.push_str(&action_to_python(action));
        out.push('\n');
    }
    out
}

/// Strip newline / carriage-return characters from a single-line
/// comment substitution. Embedded newlines would otherwise break out
/// of the comment context and let any subsequent text become Python
/// statements at column 0 of the generated script.
fn sanitise_comment(s: &str) -> String {
    s.replace(['\n', '\r'], " ")
}

/// Sanitise a script body that will be wrapped in a Python triple-quoted
/// raw-string literal. A literal `"""` inside the body would close the
/// string and let any tail become Python code. We don't try to be
/// clever about escaping — we just refuse to allow `"""` to appear inside
/// the body by inserting a zero-width seam (`"` + `\` + `""`), which
/// Python still parses as the three characters but which never
/// terminates the surrounding string literal. Callers that want to embed
/// `"""` literally can split the script themselves.
fn sanitise_triple_quoted(s: &str) -> String {
    s.replace("\"\"\"", "\"\\\"\"\"")
}

fn action_to_python(action: &MacroAction) -> String {
    match action {
        MacroAction::SwitchPanel { panel_id } => {
            format!("app.switch_panel({:?})", panel_id.as_key())
        }
        MacroAction::AddSketchEntity { entity } => match entity {
            EntityKind::Point { x, y } => {
                format!("app.add_sketch_point({x}, {y})")
            }
            EntityKind::Line { x1, y1, x2, y2 } => {
                format!("app.add_sketch_line({x1}, {y1}, {x2}, {y2})")
            }
            EntityKind::Circle { cx, cy, radius } => {
                format!("app.add_sketch_circle({cx}, {cy}, {radius})")
            }
            EntityKind::Arc {
                x1,
                y1,
                xmid,
                ymid,
                x2,
                y2,
            } => format!("app.add_sketch_arc({x1}, {y1}, {xmid}, {ymid}, {x2}, {y2})"),
        },
        MacroAction::SolveSketch { sketch } => {
            format!("app.solve_sketch({})", sketch.0)
        }
        MacroAction::AddFeature { feature, name } => {
            format!(
                "app.add_feature({:?}, {:?})  # {}",
                name,
                feature.kind_label(),
                feature.kind_label(),
            )
        }
        MacroAction::ExtrudeSketch { sketch, depth } => {
            format!("app.extrude_sketch({}, {depth})", sketch.0)
        }
        MacroAction::SaveProject { path } => {
            format!("app.save_project({path:?})")
        }
        MacroAction::LoadProject { path } => {
            format!("app.load_project({path:?})")
        }
        MacroAction::RunPython { script } => {
            // Multi-line scripts use triple-quoted raw strings; single-
            // line scripts use a quoted literal. We render via
            // `app.run_python(...)` so the generated script never has
            // to use Python's `exec` builtin directly.
            if script.contains('\n') {
                format!(
                    "app.run_python(r\"\"\"\n{}\n\"\"\")",
                    sanitise_triple_quoted(script)
                )
            } else {
                // {:?} on a String produces a debug-escaped literal,
                // which is a valid Python string literal — quotes,
                // backslashes, and non-printables all escape safely.
                format!("app.run_python({script:?})")
            }
        }
        MacroAction::SetFeatureSuppressed { id, suppressed } => {
            format!("app.set_feature_suppressed({}, {})", id.0, suppressed)
        }
        MacroAction::Step { label } => {
            format!("# step: {}", sanitise_comment(label))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::action::{EntityKind, MacroAction, PanelId};
    use valenx_feature_tree::feature::SketchRef;

    #[test]
    fn empty_macro_renders_header() {
        let m = Macro::new("Empty");
        let py = to_python(&m);
        assert!(py.contains("# Macro: Empty"));
        assert!(py.contains("import valenx"));
        assert!(py.contains("app = valenx.App.new()"));
    }

    #[test]
    fn switch_panel_emits_method_call() {
        let mut m = Macro::new("S");
        m.push(MacroAction::SwitchPanel {
            panel_id: PanelId::Sketcher,
        });
        let py = to_python(&m);
        assert!(py.contains("app.switch_panel(\"sketcher\")"));
    }

    #[test]
    fn add_sketch_circle_emits_xyz_radius() {
        let mut m = Macro::new("S");
        m.push(MacroAction::AddSketchEntity {
            entity: EntityKind::Circle {
                cx: 1.0,
                cy: 2.0,
                radius: 3.0,
            },
        });
        let py = to_python(&m);
        assert!(py.contains("app.add_sketch_circle(1, 2, 3)"));
    }

    #[test]
    fn extrude_sketch_includes_depth() {
        let mut m = Macro::new("S");
        m.push(MacroAction::ExtrudeSketch {
            sketch: SketchRef(0),
            depth: 10.0,
        });
        let py = to_python(&m);
        assert!(py.contains("app.extrude_sketch(0, 10)"));
    }

    #[test]
    fn run_python_multiline_uses_triple_quotes() {
        let mut m = Macro::new("S");
        m.push(MacroAction::RunPython {
            script: "x = 1\nprint(x)".into(),
        });
        let py = to_python(&m);
        assert!(py.contains("app.run_python(r\"\"\""));
    }

    #[test]
    fn step_emits_comment_only() {
        let mut m = Macro::new("S");
        m.push(MacroAction::Step {
            label: "Build cube".into(),
        });
        let py = to_python(&m);
        assert!(py.contains("# step: Build cube"));
    }

    /// Round-3 fix: a newline in `name` would otherwise break out of the
    /// `# Macro: ...` comment and let any subsequent line become an
    /// executable Python statement at column 0 of the generated script.
    /// The test payload uses a placeholder `INJECTED` token rather than
    /// any real exec call.
    #[test]
    fn name_with_newline_does_not_inject_python() {
        let mut m = Macro::new("innocent\nINJECTED_NAME = 1");
        m.push(MacroAction::Step {
            label: "ignored".into(),
        });
        let py = to_python(&m);
        assert!(
            !py.lines()
                .any(|l| l.trim_start().starts_with("INJECTED_NAME")),
            "name newline injected Python:\n{py}"
        );
    }

    /// Round-3 fix: same threat surface for `description` lines — each
    /// line is emitted as a `# ...` comment.
    #[test]
    fn description_with_newline_does_not_inject_python() {
        let mut m = Macro::new("M");
        m.description = "first\rINJECTED_DESC = 1".into();
        let py = to_python(&m);
        assert!(
            !py.lines()
                .any(|l| l.trim_start().starts_with("INJECTED_DESC")),
            "description CR injected Python:\n{py}"
        );
    }

    /// Round-3 fix: a literal `"""` inside a multi-line script body
    /// would otherwise close the surrounding triple-quoted raw string
    /// and let any tail become Python at column 0.
    #[test]
    fn run_python_triple_quote_does_not_inject() {
        let mut m = Macro::new("M");
        m.push(MacroAction::RunPython {
            script: "ok = 1\n\"\"\"\nINJECTED_TQ = 1\n\"\"\"".into(),
        });
        let py = to_python(&m);
        let dangerous = "\n\"\"\")\nINJECTED_TQ";
        assert!(
            !py.contains(dangerous),
            "run_python triple-quote injection survived:\n{py}"
        );
    }

    /// Round-3 fix: Step label is also emitted as a comment.
    #[test]
    fn step_label_with_newline_does_not_inject() {
        let mut m = Macro::new("M");
        m.push(MacroAction::Step {
            label: "label\nINJECTED_LABEL = 1".into(),
        });
        let py = to_python(&m);
        assert!(
            !py.lines()
                .any(|l| l.trim_start().starts_with("INJECTED_LABEL")),
            "step label injected Python:\n{py}"
        );
    }
}
