//! Generate the Python script MuJoCo consumes. Reads a model,
//! optionally sets initial qpos / qvel, drives a constant-control
//! actuator policy, records state + qpos + qvel + ctrl per sample
//! into a JSONL time series, and writes a summary.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::{DynamicsInput, ModelSource};

pub const SCRIPT_FILENAME: &str = "valenx_mujoco.py";
pub const SUMMARY_FILENAME: &str = "summary.json";
pub const TIMESERIES_FILENAME: &str = "trajectory.jsonl";

pub fn generate(input: &DynamicsInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "# Generated by valenx-adapter-mujoco — do not edit by hand.\n"
    )
    .unwrap();
    writeln!(
        s,
        "import json, math, os\nimport numpy as np\nimport mujoco\n"
    )
    .unwrap();

    // Load the model.
    let path = input.model.path();
    let path_str = path.to_string_lossy().replace('\\', "/");
    match input.model {
        ModelSource::Mjcf { .. } => {
            writeln!(s, "model = mujoco.MjModel.from_xml_path(\"{path_str}\")").unwrap();
        }
        ModelSource::Urdf { .. } => {
            writeln!(
                s,
                "# URDF load via MuJoCo 3.x native converter.\n\
                 model = mujoco.MjModel.from_xml_path(\"{path_str}\")"
            )
            .unwrap();
        }
    }
    writeln!(s, "data = mujoco.MjData(model)").unwrap();
    writeln!(s).unwrap();

    // Optional timestep override.
    if let Some(dt) = input.timestep_s {
        writeln!(s, "model.opt.timestep = {dt}").unwrap();
    }

    // Initial state.
    if !input.initial_qpos.is_empty() {
        let list = input
            .initial_qpos
            .iter()
            .map(|v| v.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(s, "qpos_init = np.array([{list}])").unwrap();
        writeln!(s, "data.qpos[:len(qpos_init)] = qpos_init[:len(data.qpos)]").unwrap();
    }
    if !input.initial_qvel.is_empty() {
        let list = input
            .initial_qvel
            .iter()
            .map(|v| v.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(s, "qvel_init = np.array([{list}])").unwrap();
        writeln!(s, "data.qvel[:len(qvel_init)] = qvel_init[:len(data.qvel)]").unwrap();
    }

    // Constant control signals, resolved by actuator name.
    if !input.ctrl.is_empty() {
        writeln!(s, "# Constant-control policy").unwrap();
        writeln!(
            s,
            "ctrl_targets = {{\n{entries}\n}}",
            entries = input
                .ctrl
                .iter()
                .map(|(k, v)| format!("    \"{k}\": {v}"))
                .collect::<Vec<_>>()
                .join(",\n")
        )
        .unwrap();
        writeln!(
            s,
            "def apply_ctrl(data, model):\n    \
                 for name, value in ctrl_targets.items():\n        \
                     idx = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_ACTUATOR, name)\n        \
                     if idx != -1:\n            \
                         data.ctrl[idx] = value"
        )
        .unwrap();
    } else {
        writeln!(
            s,
            "def apply_ctrl(data, model):\n    pass  # no control policy"
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    // Main loop.
    writeln!(
        s,
        "duration_s     = {duration}\n\
         record_every_s = {record_every}\n\
         dt             = model.opt.timestep\n\
         steps          = int(duration_s / dt)\n\
         record_stride  = max(1, int(record_every_s / dt))",
        duration = input.duration_s,
        record_every = input.record_every_s,
    )
    .unwrap();
    writeln!(s).unwrap();

    writeln!(
        s,
        "with open(\"{TIMESERIES_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             for step in range(steps):\n        \
                 apply_ctrl(data, model)\n        \
                 mujoco.mj_step(model, data)\n        \
                 if step % record_stride == 0:\n            \
                     row = {{\n                \
                         \"t\":    float(data.time),\n                \
                         \"qpos\": data.qpos.tolist(),\n                \
                         \"qvel\": data.qvel.tolist(),\n                \
                         \"ctrl\": data.ctrl.tolist(),\n            \
                     }}\n            \
                     f.write(json.dumps(row))\n            \
                     f.write(\"\\n\")"
    )
    .unwrap();
    writeln!(s).unwrap();

    // Summary.
    writeln!(
        s,
        "summary = {{\n    \
             \"valenx_adapter\": \"mujoco\",\n    \
             \"model\": \"{path_str}\",\n    \
             \"duration_s\":  duration_s,\n    \
             \"timestep_s\":  dt,\n    \
             \"step_count\":  steps,\n    \
             \"nq\":          int(model.nq),\n    \
             \"nv\":          int(model.nv),\n    \
             \"nu\":          int(model.nu),\n\
         }}\n\
         with open(\"{SUMMARY_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             json.dump(summary, f, indent=2)\n\
         print(f\"[valenx] mujoco done — {{steps}} steps, nq={{model.nq}}\")"
    )
    .unwrap();

    s
}

pub fn write_to_file(input: &DynamicsInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{DynamicsInput, ModelSource};
    use std::collections::BTreeMap;

    fn pendulum_input() -> DynamicsInput {
        let mut ctrl = BTreeMap::new();
        ctrl.insert("motor".to_string(), 0.1);
        DynamicsInput {
            model: ModelSource::Mjcf {
                path: std::path::PathBuf::from("pendulum.xml"),
            },
            duration_s: 10.0,
            timestep_s: None,
            ctrl,
            record_every_s: 0.05,
            initial_qpos: vec![0.5],
            initial_qvel: vec![0.0],
        }
    }

    #[test]
    fn script_has_expected_pieces() {
        let s = generate(&pendulum_input());
        assert!(s.contains("import mujoco"));
        assert!(s.contains("MjModel.from_xml_path(\"pendulum.xml\")"));
        assert!(s.contains("qpos_init = np.array([0.5])"));
        assert!(s.contains("ctrl_targets = {"));
        assert!(s.contains("\"motor\": 0.1"));
        assert!(s.contains("mj_step"));
        assert!(s.contains("trajectory.jsonl"));
        assert!(s.contains("summary.json"));
    }

    #[test]
    fn urdf_uses_xml_path_loader() {
        let mut input = pendulum_input();
        input.model = ModelSource::Urdf {
            path: std::path::PathBuf::from("arm.urdf"),
        };
        let s = generate(&input);
        assert!(s.contains("MjModel.from_xml_path(\"arm.urdf\")"));
    }

    #[test]
    fn empty_ctrl_produces_noop_policy() {
        let mut input = pendulum_input();
        input.ctrl = BTreeMap::new();
        let s = generate(&input);
        assert!(s.contains("pass  # no control policy"));
    }

    #[test]
    fn windows_path_gets_slashed() {
        let mut input = pendulum_input();
        input.model = ModelSource::Mjcf {
            path: std::path::PathBuf::from("models\\pendulum.xml"),
        };
        let s = generate(&input);
        assert!(s.contains("\"models/pendulum.xml\""));
    }
}
