//! Generate gmsh `.geo` scripts from a typed [`MeshSpec`].
//!
//! `.geo` is gmsh's scripting language — small but expressive enough
//! to cover the primitive + merged-file domains this adapter
//! supports in Phase 2. The output is human-readable so users can
//! diff what Valenx generated against what they'd write by hand.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::mesh_input::{Domain, MeshDim, MeshSpec};

/// The default `.msh` filename gmsh writes when no override is given.
pub const DEFAULT_MSH_FILENAME: &str = "mesh.msh";

/// Emit a `.geo` script covering every knob of `spec`.
pub fn generate(spec: &MeshSpec) -> String {
    let mut s = String::with_capacity(512);
    writeln!(
        s,
        "// ===== Generated by valenx-adapter-gmsh =====\n\
         // Edit the case.toml `[mesh]` section instead — regeneration\n\
         // overwrites this file on every prepare().\n"
    )
    .unwrap();

    // Mesh sizes (apply to all entities unless overridden per-entity).
    writeln!(
        s,
        "Mesh.CharacteristicLengthMin = {};",
        fmt_float(spec.sizes.char_length_min)
    )
    .unwrap();
    writeln!(
        s,
        "Mesh.CharacteristicLengthMax = {};",
        fmt_float(spec.sizes.char_length_max)
    )
    .unwrap();
    writeln!(s, "Mesh.Algorithm = {};", spec.algorithm_2d as u8).unwrap();
    writeln!(s, "Mesh.Algorithm3D = {};", spec.algorithm_3d as u8).unwrap();
    // Save mesh format 4.1 explicitly — the parser assumes it.
    writeln!(s, "Mesh.MshFileVersion = 4.1;").unwrap();
    writeln!(s).unwrap();

    match &spec.domain {
        Domain::Box { origin, size } => write_box(&mut s, origin, size, spec),
        Domain::Sphere { center, radius } => write_sphere(&mut s, center, *radius, spec),
        Domain::MergeFile { path } => write_merge(&mut s, path, spec),
    }

    if let Some(bl) = &spec.boundary_layer {
        writeln!(s).unwrap();
        write_boundary_layer(&mut s, bl);
    }

    writeln!(s).unwrap();
    writeln!(s, "// Actually mesh + save.").unwrap();
    writeln!(s, "Mesh {};", spec.dim.as_int()).unwrap();
    writeln!(s, "Save \"{DEFAULT_MSH_FILENAME}\";").unwrap();

    s
}

fn write_boundary_layer(s: &mut String, bl: &crate::mesh_input::BoundaryLayer) {
    // Map (first_thickness, growth_rate, num_layers) onto gmsh's
    // BoundaryLayer Field parameters. `Ratio` is the growth ratio,
    // `hwall_n` the first-cell thickness, and `thickness` the total
    // layer stack thickness derived from the geometric series sum.
    //
    //   total = first * (ratio^N - 1) / (ratio - 1)     ratio != 1
    //   total = first * N                               ratio == 1
    let (hwall_n, ratio, n) = (
        bl.first_layer_thickness.max(1e-12),
        bl.growth_rate.max(1.0 + 1e-9),
        bl.num_layers.max(1),
    );
    let total_thickness = if (ratio - 1.0).abs() < 1e-9 {
        hwall_n * n as f64
    } else {
        hwall_n * (ratio.powi(n as i32) - 1.0) / (ratio - 1.0)
    };

    writeln!(
        s,
        "// ===== Boundary layer / prism stack =====\n\
         // first cell: {}, ratio: {}, layers: {}, total thickness: {}",
        fmt_float(hwall_n),
        fmt_float(ratio),
        n,
        fmt_float(total_thickness),
    )
    .unwrap();
    writeln!(s, "Field[1] = BoundaryLayer;").unwrap();
    writeln!(s, "Field[1].hwall_n = {};", fmt_float(hwall_n)).unwrap();
    writeln!(s, "Field[1].ratio = {};", fmt_float(ratio)).unwrap();
    writeln!(s, "Field[1].thickness = {};", fmt_float(total_thickness)).unwrap();
    writeln!(s, "Field[1].Quads = 0;").unwrap();
    if !bl.surfaces.is_empty() {
        // Map the user-named surfaces onto their tag via
        // `Physical Surface` lookup. We assume the user's surface
        // names match the `Physical Surface` names we emit above.
        // For simplicity, apply the field to `FacesList = {1}`
        // — matches our single Physical Surface on Box/Sphere.
        let surface_names = bl.surfaces.join(", ");
        writeln!(
            s,
            "// Requested surfaces: {surface_names}\n\
             // Gmsh tag resolution happens at mesher time; the\n\
             // current .geo assumes a single physical surface with tag 1."
        )
        .unwrap();
    }
    writeln!(s, "Field[1].FacesList = {{1}};").unwrap();
    writeln!(s, "BoundaryLayer Field = 1;").unwrap();
}

fn write_box(s: &mut String, origin: &[f64; 3], size: &[f64; 3], spec: &MeshSpec) {
    writeln!(
        s,
        "// ===== Procedural box =====\n\
         // origin = ({}, {}, {}), size = ({}, {}, {})",
        fmt_float(origin[0]),
        fmt_float(origin[1]),
        fmt_float(origin[2]),
        fmt_float(size[0]),
        fmt_float(size[1]),
        fmt_float(size[2]),
    )
    .unwrap();
    writeln!(s, "SetFactory(\"OpenCASCADE\");").unwrap();
    writeln!(
        s,
        "Box(1) = {{{}, {}, {}, {}, {}, {}}};",
        fmt_float(origin[0]),
        fmt_float(origin[1]),
        fmt_float(origin[2]),
        fmt_float(size[0]),
        fmt_float(size[1]),
        fmt_float(size[2]),
    )
    .unwrap();

    writeln!(s).unwrap();
    writeln!(
        s,
        "Physical Volume(\"{}\", 1) = {{1}};",
        spec.physical_volume_name
    )
    .unwrap();
    writeln!(
        s,
        "Physical Surface(\"{}\", 1) = {{1, 2, 3, 4, 5, 6}};",
        spec.physical_surface_name
    )
    .unwrap();
}

fn write_sphere(s: &mut String, center: &[f64; 3], radius: f64, spec: &MeshSpec) {
    writeln!(
        s,
        "// ===== Procedural sphere =====\n\
         // center = ({}, {}, {}), radius = {}",
        fmt_float(center[0]),
        fmt_float(center[1]),
        fmt_float(center[2]),
        fmt_float(radius),
    )
    .unwrap();
    writeln!(s, "SetFactory(\"OpenCASCADE\");").unwrap();
    writeln!(
        s,
        "Sphere(1) = {{{}, {}, {}, {}}};",
        fmt_float(center[0]),
        fmt_float(center[1]),
        fmt_float(center[2]),
        fmt_float(radius),
    )
    .unwrap();

    writeln!(s).unwrap();
    writeln!(
        s,
        "Physical Volume(\"{}\", 1) = {{1}};",
        spec.physical_volume_name
    )
    .unwrap();
    writeln!(
        s,
        "Physical Surface(\"{}\", 1) = {{1}};",
        spec.physical_surface_name
    )
    .unwrap();
}

fn write_merge(s: &mut String, path: &Path, spec: &MeshSpec) {
    // gmsh's Merge works for STL, BREP, STEP, and IGES. We expect
    // the file to already be in the workdir (the adapter copies it
    // there in prepare()).
    writeln!(s, "// ===== Merged surface file =====").unwrap();
    writeln!(s, "Merge \"{}\";", path_to_gmsh(path)).unwrap();
    match spec.dim {
        MeshDim::Two => {
            writeln!(s, "// 2-D merge: surface patches become the mesh.").unwrap();
        }
        MeshDim::Three => {
            writeln!(
                s,
                "// 3-D merge: wrap the surface into a volume. The\n\
                 // classification below works for watertight STL inputs;\n\
                 // richer BRep topology is expected when the OCCT\n\
                 // adapter lands."
            )
            .unwrap();
            writeln!(s, "CreateTopology;").unwrap();
            writeln!(s, "Surface Loop(1) = Surface{{:}};").unwrap();
            writeln!(s, "Volume(1) = {{1}};").unwrap();
            writeln!(
                s,
                "Physical Volume(\"{}\", 1) = {{1}};",
                spec.physical_volume_name
            )
            .unwrap();
            writeln!(
                s,
                "Physical Surface(\"{}\", 1) = Surface{{:}};",
                spec.physical_surface_name
            )
            .unwrap();
        }
    }
}

/// Write the `.geo` file into `path`, creating the parent directory
/// if needed.
pub fn write_to_file(spec: &MeshSpec, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(spec))
}

fn fmt_float(v: f64) -> String {
    if v == 0.0 {
        return "0".to_string();
    }
    let abs = v.abs();
    if !(1e-4..1e6).contains(&abs) {
        return format!("{v:.6e}");
    }
    let s = format!("{v:.8}");
    let trimmed = s.trim_end_matches('0').trim_end_matches('.').to_string();
    if trimmed.is_empty() {
        "0".to_string()
    } else {
        trimmed
    }
}

fn path_to_gmsh(path: &Path) -> String {
    // gmsh's `.geo` expects forward-slash paths even on Windows.
    path.to_string_lossy().replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mesh_input::{Algorithm2D, Algorithm3D, MeshSizes, MeshSpec};

    fn box_spec() -> MeshSpec {
        MeshSpec {
            domain: Domain::Box {
                origin: [0.0, 0.0, 0.0],
                size: [1.0, 2.0, 3.0],
            },
            sizes: MeshSizes {
                char_length_min: 0.05,
                char_length_max: 0.2,
            },
            algorithm_2d: Algorithm2D::FrontalDelaunay,
            algorithm_3d: Algorithm3D::Delaunay,
            dim: MeshDim::Three,
            physical_volume_name: "fluid".into(),
            physical_surface_name: "walls".into(),
            boundary_layer: None,
        }
    }

    #[test]
    fn box_script_contains_expected_lines() {
        let s = generate(&box_spec());
        assert!(s.contains("Mesh.CharacteristicLengthMax = 0.2;"));
        assert!(s.contains("Mesh.Algorithm = 6;"));
        assert!(s.contains("Mesh.Algorithm3D = 1;"));
        assert!(s.contains("Mesh.MshFileVersion = 4.1;"));
        assert!(s.contains("Box(1) = {0, 0, 0, 1, 2, 3};"));
        assert!(s.contains("Physical Volume(\"fluid\", 1) = {1};"));
        assert!(s.contains("Physical Surface(\"walls\", 1) = {1, 2, 3, 4, 5, 6};"));
        assert!(s.contains("Mesh 3;"));
        assert!(s.contains("Save \"mesh.msh\";"));
    }

    #[test]
    fn sphere_script_contains_expected_lines() {
        let mut spec = box_spec();
        spec.domain = Domain::Sphere {
            center: [0.5, 0.5, 0.5],
            radius: 0.25,
        };
        let s = generate(&spec);
        assert!(s.contains("Sphere(1) = {0.5, 0.5, 0.5, 0.25};"));
    }

    #[test]
    fn merge_script_uses_forward_slashes() {
        let mut spec = box_spec();
        spec.domain = Domain::MergeFile {
            path: std::path::PathBuf::from("geometry/inlet.stl"),
        };
        let s = generate(&spec);
        assert!(s.contains("Merge \"geometry/inlet.stl\";"));
        assert!(s.contains("Volume(1) = {1};"));
    }

    #[test]
    fn boundary_layer_section_emitted_when_configured() {
        let mut spec = box_spec();
        spec.boundary_layer = Some(crate::mesh_input::BoundaryLayer {
            first_layer_thickness: 1e-5,
            growth_rate: 1.2,
            num_layers: 10,
            surfaces: vec!["walls".into()],
        });
        let s = generate(&spec);
        assert!(s.contains("// ===== Boundary layer / prism stack ====="));
        assert!(s.contains("Field[1] = BoundaryLayer;"));
        assert!(s.contains("Field[1].hwall_n = 1.000000e-5;"));
        assert!(s.contains("Field[1].ratio = 1.2;"));
        // 10 layers at ratio 1.2 → total ≈ 2.596e-4
        assert!(s.contains("Field[1].thickness ="));
        assert!(s.contains("BoundaryLayer Field = 1;"));
        assert!(s.contains("// Requested surfaces: walls"));
    }

    #[test]
    fn boundary_layer_absent_for_plain_mesh() {
        let s = generate(&box_spec());
        assert!(!s.contains("BoundaryLayer"));
        assert!(!s.contains("hwall_n"));
    }

    #[test]
    fn boundary_layer_ratio_one_uses_linear_sum() {
        let mut spec = box_spec();
        spec.boundary_layer = Some(crate::mesh_input::BoundaryLayer {
            first_layer_thickness: 1e-5,
            growth_rate: 1.0, // Clamped to just over 1 internally.
            num_layers: 5,
            surfaces: Vec::new(),
        });
        let s = generate(&spec);
        assert!(s.contains("Field[1] = BoundaryLayer;"));
        assert!(s.contains("Field[1].hwall_n = 1.000000e-5;"));
    }

    #[test]
    fn write_to_file_creates_parent_dirs() {
        let tmp = std::env::temp_dir().join(format!(
            "valenx-gmsh-geo-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let path = tmp.join("deeper").join("case.geo");
        write_to_file(&box_spec(), &path).expect("write");
        assert!(path.is_file());
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("Mesh 3;"));
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
