//! Generate a deterministic Python script that drives PyBaMM for
//! the configured battery case.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::{BatteryInput, Protocol};

pub const SCRIPT_FILENAME: &str = "valenx_pybamm.py";
pub const SUMMARY_FILENAME: &str = "summary.json";
pub const TIMESERIES_FILENAME: &str = "timeseries.csv";

pub fn generate(input: &BatteryInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "# Generated by valenx-adapter-pybamm — do not edit by hand.\n"
    )
    .unwrap();

    writeln!(s, "import json, csv\nimport pybamm\n").unwrap();

    // Model + parameters.
    //
    // Round-19 H2: `input.parameter_set` is user-controlled (read
    // verbatim from case.toml in case_input.rs). Pre-fix this site
    // embedded it as `"{}"`, so a value like
    // `parameter_set = "Chen2020\");\nimport os\nx = pybamm.ParameterValues(\""`
    // would close the literal and inject statement-level Python the
    // user controls. Route through
    // [`valenx_core::adapter_helpers::python_str_repr`] so every
    // Python-escape gets handled consistently (`\`, `"`, `\n`, `\r`,
    // `\t`, control bytes). The `pybamm_class()` form is static —
    // it comes from an enum — so it doesn't need the escape, but the
    // ParameterValues argument is the injection vector.
    writeln!(
        s,
        "model = pybamm.lithium_ion.{}()",
        input.model.pybamm_class()
    )
    .unwrap();
    writeln!(
        s,
        "param = pybamm.ParameterValues(\"{}\")",
        valenx_core::adapter_helpers::python_str_repr(&input.parameter_set)
    )
    .unwrap();
    writeln!(s).unwrap();

    // Initial SOC is applied by re-scaling the initial concentrations
    // per PyBaMM's own `set_initial_stoichiometries` hook on Param-
    // eterValues. Works for all standard built-in parameter sets.
    writeln!(
        s,
        "param.set_initial_stoichiometries({:.6})",
        input.initial_soc
    )
    .unwrap();
    writeln!(s).unwrap();

    // Experiment / protocol.
    writeln!(s, "# Protocol").unwrap();
    match &input.protocol {
        Protocol::CcDischarge {
            current_a,
            cutoff_voltage_v,
        } => {
            // pybamm.Experiment supports a rich DSL; a single-step
            // "Discharge at X A until Y V" is the cleanest way to
            // describe a CC-discharge.
            writeln!(
                s,
                "experiment = pybamm.Experiment([\n    \
                     f\"Discharge at {current_a} A until {cutoff_voltage_v} V\"\n\
                 ])",
            )
            .unwrap();
        }
        Protocol::Cccv {
            current_a,
            voltage_v,
            end_current_a,
        } => {
            let abs_current = current_a.abs();
            writeln!(
                s,
                "experiment = pybamm.Experiment([\n    \
                     f\"Charge at {abs_current} A until {voltage_v} V\",\n    \
                     f\"Hold at {voltage_v} V until {end_current_a} A\"\n\
                 ])",
            )
            .unwrap();
        }
    }
    writeln!(s).unwrap();

    writeln!(
        s,
        "sim = pybamm.Simulation(model, parameter_values=param, experiment=experiment)"
    )
    .unwrap();
    writeln!(s, "solution = sim.solve()").unwrap();
    writeln!(s).unwrap();

    // Extract + decimate the time series.
    writeln!(
        s,
        "time_s    = solution[\"Time [s]\"].entries\n\
         voltage_v = solution[\"Voltage [V]\"].entries\n\
         current_a = solution[\"Current [A]\"].entries"
    )
    .unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "# Decimate so the output file stays readable.\n\
         SAMPLE_DT = {sample_dt}\n\
         keep = [0]\n\
         last_t = time_s[0]\n\
         for i in range(1, len(time_s)):\n    \
             if time_s[i] - last_t >= SAMPLE_DT:\n        \
                 keep.append(i)\n        \
                 last_t = time_s[i]\n\
         if keep[-1] != len(time_s) - 1:\n    \
             keep.append(len(time_s) - 1)",
        sample_dt = input.sample_every_s
    )
    .unwrap();
    writeln!(s).unwrap();

    // Write CSV + JSON summary.
    writeln!(
        s,
        "with open(\"{TIMESERIES_FILENAME}\", \"w\", newline=\"\", encoding=\"utf-8\") as f:\n    \
             w = csv.writer(f)\n    \
             w.writerow([\"t_s\", \"voltage_v\", \"current_a\"])\n    \
             for i in keep:\n        \
                 w.writerow([float(time_s[i]), float(voltage_v[i]), float(current_a[i])])"
    )
    .unwrap();
    writeln!(s).unwrap();
    // Round-19 H2: `pset` is user-controlled. Same escape pattern as
    // the ParameterValues call site above — without it, a hostile
    // parameter_set field would close the dict-value literal and
    // inject statement-level Python before the summary write. `model`
    // comes from a static enum so it doesn't need escaping.
    writeln!(
        s,
        "summary = {{\n    \
             \"valenx_adapter\": \"pybamm\",\n    \
             \"model\": \"{model}\",\n    \
             \"parameter_set\": \"{pset}\",\n    \
             \"samples\": len(keep),\n    \
             \"duration_s\": float(time_s[keep[-1]]),\n    \
             \"voltage_start_v\": float(voltage_v[0]),\n    \
             \"voltage_end_v\":   float(voltage_v[keep[-1]]),\n    \
             \"initial_soc\": {soc},\n\
         }}\n\
         with open(\"{SUMMARY_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             json.dump(summary, f, indent=2)\n\
         print(f\"[valenx] pybamm done — {{summary['samples']}} samples, \
         final voltage {{summary['voltage_end_v']:.3f}} V\")",
        model = input.model.pybamm_class(),
        pset = valenx_core::adapter_helpers::python_str_repr(&input.parameter_set),
        soc = input.initial_soc
    )
    .unwrap();

    s
}

pub fn write_to_file(input: &BatteryInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{BatteryInput, ModelKind, Protocol};

    fn dfn_cc_input() -> BatteryInput {
        BatteryInput {
            model: ModelKind::Dfn,
            parameter_set: "Chen2020".into(),
            protocol: Protocol::CcDischarge {
                current_a: 5.0,
                cutoff_voltage_v: 2.5,
            },
            initial_soc: 1.0,
            time_horizon_s: 3600.0,
            sample_every_s: 30.0,
        }
    }

    #[test]
    fn cc_script_has_expected_lines() {
        let s = generate(&dfn_cc_input());
        assert!(s.contains("import pybamm"));
        assert!(s.contains("pybamm.lithium_ion.DFN()"));
        assert!(s.contains("pybamm.ParameterValues(\"Chen2020\")"));
        assert!(s.contains("set_initial_stoichiometries(1.000000)"));
        assert!(s.contains("Discharge at 5 A until 2.5 V"));
        assert!(s.contains("pybamm.Experiment"));
        assert!(s.contains("pybamm.Simulation"));
        assert!(s.contains("solution = sim.solve()"));
        assert!(s.contains("timeseries.csv"));
        assert!(s.contains("summary.json"));
        assert!(s.contains("SAMPLE_DT = 30"));
    }

    #[test]
    fn cccv_script_generates_two_step_experiment() {
        let mut input = dfn_cc_input();
        input.protocol = Protocol::Cccv {
            current_a: -2.5,
            voltage_v: 4.2,
            end_current_a: 0.1,
        };
        let s = generate(&input);
        assert!(s.contains("Charge at 2.5 A until 4.2 V"));
        assert!(s.contains("Hold at 4.2 V until 0.1 A"));
    }

    #[test]
    fn spm_model_uses_spm_class() {
        let mut input = dfn_cc_input();
        input.model = ModelKind::Spm;
        let s = generate(&input);
        assert!(s.contains("pybamm.lithium_ion.SPM()"));
    }

    /// Round-19 H2 RED→GREEN: a hostile `parameter_set` value that
    /// tries to close the Python string literal and inject statement-
    /// level Python MUST NOT escape the literal in the emitted script.
    /// Pre-fix `format!("\"{}\"", input.parameter_set)` interpolated
    /// the value verbatim — any `"` + `\n` payload broke out of the
    /// quoted region and turned the next line into a Python statement
    /// the user (case.toml author) controls. With the
    /// `python_str_repr` helper the entire payload becomes one
    /// escaped literal so the surrounding script structure is
    /// preserved.
    #[test]
    fn parameter_set_injection_payload_is_escaped() {
        let payload = "Chen2020\");\nimport os\nx = pybamm.ParameterValues(\"";
        let mut input = dfn_cc_input();
        input.parameter_set = payload.into();
        let script = generate(&input);
        // The dangerous raw shape — `");` followed by `\n` —
        // MUST NOT appear at the byte level in the script.
        assert!(
            !script.contains("\");\nimport os"),
            "raw `\");\\nimport os` injection survived escape: \
             searching script for the bare payload"
        );
        // The next statement after `pybamm.ParameterValues(...)` must
        // STILL be `param.set_initial_stoichiometries(...)` (or
        // similar — at least an indented set_initial / next dict
        // key). If injection had succeeded we'd see `import os`
        // immediately following the closing quote of the literal.
        let needle = "pybamm.ParameterValues(\"";
        let after = script
            .split(needle)
            .nth(1)
            .expect("script must contain ParameterValues call");
        // The escaped payload begins with `Chen2020\"` (escaped quote)
        // not `Chen2020");`. The first chars after the opening quote
        // must NOT be the raw payload preamble.
        assert!(
            !after.starts_with("Chen2020\");"),
            "raw payload survived past the opening quote: {}",
            &after[..after.len().min(80)]
        );
    }
}
