//! POD–Galerkin projection of a full-order linear operator.
//!
//! Given a full-order linear system `dx/dt = A x` (or `x_{k+1} = A x_k`) and a
//! POD basis `Uᵣ` ([`crate::pod::PodBasis`]), the **Galerkin** reduced operator
//! is the orthogonal projection of `A` onto the reduced subspace:
//!
//! ```text
//! Aᵣ = Uᵣᵀ A Uᵣ        (r × r)
//! ```
//!
//! and a full state maps to/from reduced coordinates via `q = Uᵣᵀ x`,
//! `x ≈ Uᵣ q`. The reduced dynamics `dq/dt = Aᵣ q` are then integrated in `r`
//! dimensions instead of the full state dimension.
//!
//! This is the *intrusive* counterpart to [`crate::opinf`]: it needs the actual
//! full-order operator `A`, whereas OpInf infers `Aᵣ` from data. For a linear
//! `A` whose dynamics stay in the POD subspace, the two agree.
//!
//! ## Affine term
//!
//! An optional constant forcing `b` (so `dx/dt = A x + b`) projects to
//! `bᵣ = Uᵣᵀ b`; [`galerkin_affine`] returns the pair `(Aᵣ, bᵣ)`.

use nalgebra::{DMatrix, DVector};

use crate::error::RomError;
use crate::pod::PodBasis;

/// Project a full-order linear operator `A` onto the POD basis: `Aᵣ = Uᵣᵀ A Uᵣ`.
///
/// `A` must be square with side equal to the basis state dimension.
///
/// # Errors
/// - [`RomError::DimensionMismatch`] if `A` is not square or its size differs
///   from the basis state dimension.
/// - [`RomError::NonFinite`] if `A` holds a non-finite entry.
pub fn galerkin_operator(
    basis: &PodBasis,
    a_full: &DMatrix<f64>,
) -> Result<DMatrix<f64>, RomError> {
    let n = basis.state_dim();
    if a_full.nrows() != n || a_full.ncols() != n {
        return Err(RomError::DimensionMismatch {
            what: "Galerkin operator (must be n x n)",
            expected: n,
            got: a_full.nrows().max(a_full.ncols()),
        });
    }
    if a_full.iter().any(|v| !v.is_finite()) {
        return Err(RomError::NonFinite {
            what: "Galerkin operator",
        });
    }
    let u = basis.modes();
    Ok(u.transpose() * a_full * u)
}

/// Project a full-order linear system with affine forcing `dx/dt = A x + b`,
/// returning the reduced pair `(Aᵣ, bᵣ) = (Uᵣᵀ A Uᵣ, Uᵣᵀ b)`.
///
/// # Errors
/// - As [`galerkin_operator`] for `a_full`.
/// - [`RomError::DimensionMismatch`] if `b.len() != basis.state_dim()`.
/// - [`RomError::NonFinite`] if `b` holds a non-finite entry.
pub fn galerkin_affine(
    basis: &PodBasis,
    a_full: &DMatrix<f64>,
    b_full: &DVector<f64>,
) -> Result<(DMatrix<f64>, DVector<f64>), RomError> {
    let a_r = galerkin_operator(basis, a_full)?;
    let n = basis.state_dim();
    if b_full.len() != n {
        return Err(RomError::DimensionMismatch {
            what: "Galerkin forcing vector",
            expected: n,
            got: b_full.len(),
        });
    }
    if b_full.iter().any(|v| !v.is_finite()) {
        return Err(RomError::NonFinite {
            what: "Galerkin forcing",
        });
    }
    let b_r = basis.modes().transpose() * b_full;
    Ok((a_r, b_r))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::snapshots::Snapshots;
    use nalgebra::DMatrix;

    /// If the snapshots are generated by a linear operator A whose dynamics
    /// live in a 2-D invariant subspace, the Galerkin reduced operator on the
    /// POD basis of those snapshots must be similar to A restricted to that
    /// subspace — i.e. its eigenvalues match the active eigenvalues of A.
    #[test]
    fn galerkin_preserves_active_eigenvalues() {
        // 4-D system, block-diagonal: a 2-D rotation-decay block that is
        // excited, plus a 2-D block left unexcited (zero in the data).
        let theta = 0.3_f64;
        let s = 0.95_f64;
        #[rustfmt::skip]
        let a_full = DMatrix::from_row_slice(4, 4, &[
            s*theta.cos(), -s*theta.sin(), 0.0, 0.0,
            s*theta.sin(),  s*theta.cos(), 0.0, 0.0,
            0.0, 0.0, 0.5, 0.0,
            0.0, 0.0, 0.0, 0.2,
        ]);
        // Excite only the first block.
        let mut state = DVector::from_row_slice(&[1.0, 0.0, 0.0, 0.0]);
        let mut cols = Vec::new();
        for _ in 0..40 {
            cols.push(vec![state[0], state[1], state[2], state[3]]);
            state = &a_full * &state;
        }
        let snaps = Snapshots::from_columns(&cols).unwrap();
        let basis = PodBasis::fit(&snaps, 1.0).unwrap();
        assert_eq!(basis.rank(), 2, "active subspace should be 2-D");

        let a_r = galerkin_operator(&basis, &a_full).unwrap();
        assert_eq!(a_r.nrows(), 2);

        // Eigenvalues of Aᵣ should be s·e^{±iθ}.
        let evs = a_r.complex_eigenvalues();
        let target_mag = s;
        for ev in evs.iter() {
            assert!(
                (ev.norm() - target_mag).abs() < 1e-9,
                "eig magnitude {} != {}",
                ev.norm(),
                target_mag
            );
        }
    }

    #[test]
    fn galerkin_operator_is_orthogonal_projection() {
        // For an orthonormal basis, Uᵀ A U has the right shape and reduces a
        // symmetric A's quadratic form consistently.
        let theta = 0.5;
        #[rustfmt::skip]
        let a_full = DMatrix::from_row_slice(3, 3, &[
            2.0, 0.0, 0.0,
            0.0, 1.0, 0.0,
            0.0, 0.0, 0.3,
        ]);
        // Snapshots spanning the first two axes.
        let mut cols = Vec::new();
        for k in 0..10 {
            let t = k as f64 * 0.1 + theta;
            cols.push(vec![t.cos(), t.sin(), 0.0]);
        }
        let snaps = Snapshots::from_columns(&cols).unwrap();
        let basis = PodBasis::fit(&snaps, 1.0).unwrap();
        let a_r = galerkin_operator(&basis, &a_full).unwrap();
        // q = Uᵀx then Uᵀ A U q == Uᵀ (A (U q)).
        let q = DVector::from_row_slice(&vec![0.7; basis.rank()]);
        let lhs = &a_r * &q;
        let rhs = basis.modes().transpose() * (&a_full * (basis.modes() * &q));
        assert!((lhs - rhs).norm() < 1e-12);
    }

    #[test]
    fn rejects_non_square_operator() {
        let cols = vec![vec![1.0, 0.0], vec![0.0, 1.0]];
        let snaps = Snapshots::from_columns(&cols).unwrap();
        let basis = PodBasis::fit(&snaps, 1.0).unwrap();
        let a = DMatrix::<f64>::zeros(2, 3);
        assert_eq!(
            galerkin_operator(&basis, &a).unwrap_err().code(),
            "dimension_mismatch"
        );
    }

    #[test]
    fn rejects_size_mismatch() {
        let cols = vec![vec![1.0, 0.0, 0.0], vec![0.0, 1.0, 0.0]];
        let snaps = Snapshots::from_columns(&cols).unwrap();
        let basis = PodBasis::fit(&snaps, 1.0).unwrap();
        let a = DMatrix::<f64>::identity(2, 2); // wrong size (basis is 3-D)
        assert_eq!(
            galerkin_operator(&basis, &a).unwrap_err().code(),
            "dimension_mismatch"
        );
    }

    #[test]
    fn affine_projects_forcing() {
        let cols = vec![vec![1.0, 0.0], vec![0.0, 1.0]];
        let snaps = Snapshots::from_columns(&cols).unwrap();
        let basis = PodBasis::fit(&snaps, 1.0).unwrap();
        let a = DMatrix::<f64>::identity(2, 2);
        let b = DVector::from_row_slice(&[1.0, 2.0]);
        let (a_r, b_r) = galerkin_affine(&basis, &a, &b).unwrap();
        assert_eq!(a_r.nrows(), 2);
        assert_eq!(b_r.len(), 2);
        // Uᵀ b has the same norm as b when U spans the full space.
        assert!((b_r.norm() - b.norm()).abs() < 1e-12);
    }
}
