//! Generate the Python script that `FreeCADCmd` executes to do our
//! work. The script is deterministic given a [`GeometryImportInput`]
//! so snapshot tests catch accidental regressions.
//!
//! Shape of the generated script:
//!
//! 1. Read the import path from argv (the CLI injects it).
//! 2. Open the file with `Part.open` / `FreeCAD.open`.
//! 3. Walk `FreeCAD.ActiveDocument.Objects`, collecting shapes.
//! 4. Export the bundle to every format the user asked for.
//! 5. Emit `summary.json` with parts, bounding box, total volume /
//!    area, and optionally a feature-tree summary.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::{ExportFormat, GeometryImportInput, Primitive};

/// Filename FreeCAD-side code expects for its summary output.
pub const SUMMARY_FILENAME: &str = "summary.json";
/// Filename we give the generated Python script.
pub const SCRIPT_FILENAME: &str = "valenx_import.py";

/// Emit the Python script as a string.
pub fn generate(input: &GeometryImportInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "# Generated by valenx-adapter-freecad — do not edit by hand.\n\
         # Re-running `prepare()` overwrites this file.\n"
    )
    .unwrap();

    writeln!(
        s,
        "import sys, os, json\n\
         import FreeCAD"
    )
    .unwrap();
    // Part / Mesh imports are gated by what the script uses below.
    writeln!(s, "import Part").unwrap();
    if input.exports.contains(&ExportFormat::Stl) {
        writeln!(s, "import Mesh").unwrap();
    }
    writeln!(s).unwrap();

    // Two source modes: procedural primitive (no source_path needed)
    // or open-an-existing-file. The adapter picks based on whether
    // `input.primitive` is set.
    if let Some(prim) = input.primitive {
        write_primitive_block(&mut s, prim);
    } else {
        // Source path from argv (the adapter hands it in by name).
        writeln!(
            s,
            "source_path = sys.argv[-1]\n\
             print(f\"[valenx] opening {{source_path}}\")\n"
        )
        .unwrap();

        // Dispatch the opener on the declared format.
        match input.source_format.freecad_opener() {
            "FreeCAD.open" => writeln!(s, "doc = FreeCAD.open(source_path)").unwrap(),
            // Part.open creates + activates a document.
            _ => writeln!(s, "Part.open(source_path)\ndoc = FreeCAD.ActiveDocument").unwrap(),
        }
        writeln!(
            s,
            "if doc is None:\n    \
                 raise SystemExit(f\"FreeCAD failed to open {{source_path}}\")"
        )
        .unwrap();
        writeln!(s).unwrap();
    }

    // Collect every object that carries a Shape, which is what every
    // Part.open export spits out.
    writeln!(
        s,
        "shapes = []\n\
         parts = []\n\
         for obj in doc.Objects:\n    \
             if getattr(obj, \"Shape\", None) is not None:\n        \
                 shapes.append(obj.Shape)\n        \
                 parts.append({{\"name\": obj.Label, \"type\": obj.TypeId}})"
    )
    .unwrap();
    writeln!(
        s,
        "if not shapes:\n    \
             raise SystemExit(\"[valenx] no Part.Shape-bearing objects found in document\")\n"
    )
    .unwrap();

    // Build a compound for bbox / volume computation.
    writeln!(
        s,
        "compound = Part.makeCompound(shapes)\n\
         bb = compound.BoundBox\n"
    )
    .unwrap();

    // Exports.
    for fmt in &input.exports {
        match fmt {
            ExportFormat::Stl => {
                writeln!(
                    s,
                    "mesh_shapes = [o for o in doc.Objects if getattr(o, \"Shape\", None) is not None]\n\
                     Mesh.export(mesh_shapes, \"output.stl\", tolerance={:.6})",
                    input.stl_deviation_mm,
                )
                .unwrap();
            }
            ExportFormat::Brep => {
                writeln!(s, "compound.exportBrep(\"output.brep\")").unwrap();
            }
            ExportFormat::Step => {
                writeln!(s, "compound.exportStep(\"output.step\")").unwrap();
            }
            ExportFormat::Iges => {
                // FreeCAD's TopoShape API doesn't have a direct
                // exportIges method on the compound, so we go
                // through the Import module which is the same
                // path Tools -> Export defaults to.
                writeln!(
                    s,
                    "import Import\n\
                     Import.export(mesh_shapes if 'mesh_shapes' in dir() else [o for o in doc.Objects if getattr(o, \"Shape\", None) is not None], \"output.iges\")"
                )
                .unwrap();
            }
        }
    }
    writeln!(s).unwrap();

    // Feature-tree summary (optional).
    if input.emit_feature_tree {
        writeln!(
            s,
            "feature_tree = []\n\
             for obj in doc.Objects:\n    \
                 feature_tree.append({{\n        \
                     \"name\": obj.Label,\n        \
                     \"type\": obj.TypeId,\n        \
                     \"visible\": bool(getattr(obj, \"Visibility\", True)),\n        \
                     \"has_shape\": getattr(obj, \"Shape\", None) is not None,\n    \
                 }})"
        )
        .unwrap();
    } else {
        writeln!(s, "feature_tree = []").unwrap();
    }
    writeln!(s).unwrap();

    // Write summary.json.
    writeln!(
        s,
        "summary = {{\n    \
             \"valenx_adapter\": \"freecad\",\n    \
             \"source\": source_path,\n    \
             \"parts\": parts,\n    \
             \"feature_tree\": feature_tree,\n    \
             \"bounding_box\": {{\n        \
                 \"min\": [bb.XMin, bb.YMin, bb.ZMin],\n        \
                 \"max\": [bb.XMax, bb.YMax, bb.ZMax],\n    \
             }},\n    \
             \"volume\": float(compound.Volume),\n    \
             \"area\":   float(compound.Area),\n\
         }}\n\
         with open(\"{SUMMARY_FILENAME}\", \"w\", encoding=\"utf-8\") as f:\n    \
             json.dump(summary, f, indent=2)\n\
         print(\"[valenx] wrote {SUMMARY_FILENAME}\")"
    )
    .unwrap();

    s
}

/// Write the generated script to `path`, creating parents.
/// Emit the procedural primitive-creation block. Replaces the
/// "open source_path" branch when the user supplied a
/// `[geometry.primitive]` block in their case.toml.
fn write_primitive_block(s: &mut String, prim: Primitive) {
    writeln!(s, "print(\"[valenx] generating procedural primitive\")").unwrap();
    writeln!(s, "doc = FreeCAD.newDocument(\"valenx\")").unwrap();
    match prim {
        Primitive::Cube { x, y, z } => {
            writeln!(
                s,
                "shape = Part.makeBox({x}, {y}, {z})\n\
                 obj = doc.addObject(\"Part::Feature\", \"cube\")\n\
                 obj.Shape = shape\n\
                 obj.Label = \"cube\""
            )
            .unwrap();
        }
        Primitive::Cylinder { radius, height } => {
            writeln!(
                s,
                "shape = Part.makeCylinder({radius}, {height})\n\
                 obj = doc.addObject(\"Part::Feature\", \"cylinder\")\n\
                 obj.Shape = shape\n\
                 obj.Label = \"cylinder\""
            )
            .unwrap();
        }
        Primitive::Sphere { radius } => {
            writeln!(
                s,
                "shape = Part.makeSphere({radius})\n\
                 obj = doc.addObject(\"Part::Feature\", \"sphere\")\n\
                 obj.Shape = shape\n\
                 obj.Label = \"sphere\""
            )
            .unwrap();
        }
    }
    writeln!(s, "doc.recompute()").unwrap();
    writeln!(s).unwrap();
}

pub fn write_to_file(input: &GeometryImportInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{ExportFormat, GeometryImportInput, Primitive, SourceFormat};

    fn step_input() -> GeometryImportInput {
        GeometryImportInput {
            source: std::path::PathBuf::from("bracket.step"),
            source_format: SourceFormat::Step,
            exports: vec![ExportFormat::Stl, ExportFormat::Brep],
            stl_deviation_mm: 0.05,
            emit_feature_tree: true,
            primitive: None,
        }
    }

    #[test]
    fn primitive_cube_emits_makebox() {
        let mut input = step_input();
        input.primitive = Some(Primitive::Cube {
            x: 10.0,
            y: 20.0,
            z: 30.0,
        });
        let script = generate(&input);
        // Procedural path picked.
        assert!(
            script.contains("Part.makeBox(10, 20, 30)"),
            "expected makeBox with cube dims, got:\n{script}"
        );
        // No source-path opening logic.
        assert!(!script.contains("Part.open(source_path)"));
        assert!(!script.contains("source_path = sys.argv"));
        // Document creation + recompute still happen.
        assert!(script.contains("FreeCAD.newDocument"));
        assert!(script.contains("doc.recompute()"));
    }

    #[test]
    fn primitive_cylinder_emits_makecylinder() {
        let mut input = step_input();
        input.primitive = Some(Primitive::Cylinder {
            radius: 5.0,
            height: 50.0,
        });
        let script = generate(&input);
        assert!(script.contains("Part.makeCylinder(5, 50)"));
    }

    #[test]
    fn primitive_sphere_emits_makesphere() {
        let mut input = step_input();
        input.primitive = Some(Primitive::Sphere { radius: 7.5 });
        let script = generate(&input);
        assert!(script.contains("Part.makeSphere(7.5)"));
    }

    #[test]
    fn script_covers_open_shapes_exports_summary() {
        let script = generate(&step_input());
        // Imports.
        assert!(script.contains("import FreeCAD"));
        assert!(script.contains("import Part"));
        assert!(script.contains("import Mesh"));
        // Open.
        assert!(script.contains("Part.open(source_path)"));
        assert!(script.contains("doc = FreeCAD.ActiveDocument"));
        // Shape collection.
        assert!(script.contains("for obj in doc.Objects"));
        // Exports.
        assert!(script.contains("Mesh.export"));
        assert!(script.contains("tolerance=0.050000"));
        assert!(script.contains("compound.exportBrep"));
        // Summary.
        assert!(script.contains("summary.json"));
        assert!(script.contains("bounding_box"));
        assert!(script.contains("feature_tree"));
    }

    #[test]
    fn fcstd_uses_freecad_open() {
        let mut input = step_input();
        input.source_format = SourceFormat::Fcstd;
        let script = generate(&input);
        assert!(script.contains("doc = FreeCAD.open(source_path)"));
        assert!(!script.contains("Part.open(source_path)"));
    }

    #[test]
    fn stl_only_export_skips_brep() {
        let mut input = step_input();
        input.exports = vec![ExportFormat::Stl];
        let script = generate(&input);
        assert!(script.contains("Mesh.export"));
        assert!(!script.contains("exportBrep"));
        assert!(!script.contains("exportStep"));
    }

    #[test]
    fn step_export_uses_export_step_call() {
        let mut input = step_input();
        input.exports = vec![ExportFormat::Step];
        let script = generate(&input);
        assert!(script.contains("compound.exportStep(\"output.step\")"));
    }

    #[test]
    fn feature_tree_opt_in() {
        let mut input = step_input();
        input.emit_feature_tree = false;
        let script = generate(&input);
        // Still populates the variable so the summary JSON shape stays
        // consistent, just as an empty list.
        assert!(script.contains("feature_tree = []"));
        assert!(!script.contains("for obj in doc.Objects:\n    feature_tree.append"));
    }

    #[test]
    fn iges_export_emits_import_module_call() {
        // FreeCAD's TopoShape API doesn't have a direct
        // exportIges; the Import module is the canonical path.
        let mut input = step_input();
        input.exports = vec![ExportFormat::Iges];
        let script = generate(&input);
        assert!(script.contains("import Import"), "got:\n{script}");
        assert!(
            script.contains("Import.export(") && script.contains("\"output.iges\""),
            "got:\n{script}"
        );
    }

    #[test]
    fn iges_export_extension_is_lowercase_iges() {
        // ParaView / OpenSCAD / older CAM tools all expect .iges
        // (lowercase, four-char) — anything else (.IGS, .igs)
        // would still be a valid file but trips downstream
        // path-pattern matching.
        assert_eq!(ExportFormat::Iges.extension(), "iges");
    }
}
