//! Sobol' low-discrepancy (quasi-random) sequence.
//!
//! A *low-discrepancy* sequence fills the unit hypercube `[0, 1)^d` much more
//! evenly than independent pseudo-random points: instead of the clustering and
//! gaps inherent to uniform random sampling, successive Sobol' points
//! deterministically avoid one another. Used as the sample set for a
//! *quasi-Monte-Carlo* (QMC) integral, this gives an asymptotic error of
//! roughly `O((log n)^d / n)` for smooth integrands — markedly faster than the
//! `O(1/√n)` of plain Monte-Carlo (see [`crate::sampling::monte_carlo`]) at the
//! same `n`.
//!
//! This is the Sobol' **point sequence** — distinct from the Sobol'
//! **sensitivity indices** in [`crate::sensitivity`], which only share the
//! mathematician's name.
//!
//! ## Construction
//!
//! Each dimension is generated by the classic Sobol' recurrence over the binary
//! field. Dimension 0 uses direction numbers `v_k = 2^(32-k)` (single shifting
//! bits); every further dimension uses a set of *direction numbers* `v_k`
//! derived from a primitive polynomial together with published initial
//! *direction integers* `m_k`. Points are advanced by the standard
//! **Antonov–Saleev Gray-code recurrence**: point `i` is point `i−1`
//! exclusive-or'd with the single direction number selected by the lowest zero
//! bit of `i−1`. This is the de-facto standard construction (Bratley–Fox ACM
//! TOMS Alg. 659; Joe–Kuo), and it is what every reference Sobol' generator
//! emits, so the points here match published Sobol' values directly. A prefix
//! of length `n` is itself a valid, reproducible Sobol' net (prefix property).
//! The direction integers are the Joe–Kuo `new-joe-kuo-6.21201` table.
//!
//! Note that the Gray-code recurrence visits the dyadic rationals in a
//! different *order* from the plain radical-inverse (van der Corput) sequence —
//! e.g. dimension 0 yields `0, ½, ¾, ¼, ⅜, ⅞, ⅝, ⅛, …` rather than the
//! radical-inverse `0, ½, ¼, ¾, ⅛, …`. Both are equidistributed; the Gray-code
//! order is the conventional Sobol' output and is what the tests pin to.
//!
//! ## Supported dimension limit — fail-loud above it
//!
//! Direction integers are tabulated here for **up to [`MAX_DIM`] = 21
//! dimensions**. [`sobol_sequence`] returns [`UqError::OutOfRange`] for any
//! `dim > MAX_DIM` rather than silently fabricating directions for an
//! unsupported dimension — a wrong quasi-random point would corrupt an integral
//! without any visible failure, which the project's correctness rules forbid.
//! (The Joe–Kuo file extends to 21201 dimensions; only the leading block is
//! vendored to keep the crate dependency-light. Extending [`MAX_DIM`] is purely
//! a matter of pasting more rows from that public-domain table.)
//!
//! ## Honesty / scope caveats
//!
//! * The QMC convergence advantage assumes a **smooth** (or
//!   bounded-variation) integrand and degrades in high dimension — the
//!   `(log n)^d` factor eventually dominates. For rough integrands QMC can do
//!   no better than MC.
//! * The sequence is **deterministic**: there is no randomisation
//!   (no scrambling / digital shift), so it yields a single estimate with no
//!   built-in error bar. Randomised QMC (for a variance estimate) is a
//!   documented future extension, not provided here.
//! * Best results use a number of points that is a **power of two** (the
//!   sequence is balanced at those prefixes); other `n` are still valid but
//!   slightly less uniform.

use crate::error::UqError;

/// Number of bits used per coordinate. With 32 bits the finest spacing is
/// `2⁻³²`, so a sequence of any practical length stays well clear of the grid
/// resolution.
const NUM_BITS: usize = 32;

/// Maximum supported dimension (see the module-level note). Direction integers
/// are vendored for dimensions `1..=MAX_DIM`.
pub const MAX_DIM: usize = 21;

/// Generate the first `n` points of the Sobol' sequence in `[0, 1)^dim`.
///
/// Returns a `Vec` of `n` points, each a `Vec<f64>` of length `dim` with every
/// coordinate in `[0, 1)`. The result is fully deterministic: the same
/// `(n, dim)` always yields the same points, and the first `m < n` of them are
/// identical to a separate `sobol_sequence(m, dim)` call (prefix property).
///
/// The conventional first point (index 0) is the origin `0^dim`.
///
/// # Errors
/// * [`UqError::OutOfRange`] if `dim == 0` or `dim > MAX_DIM`.
///
/// # Example
/// ```
/// use valenx_uq::sobol::sobol_sequence;
/// let pts = sobol_sequence(4, 2).unwrap();
/// assert_eq!(pts[0], vec![0.0, 0.0]);
/// assert_eq!(pts[1], vec![0.5, 0.5]);
/// assert_eq!(pts[2], vec![0.75, 0.25]);
/// assert_eq!(pts[3], vec![0.25, 0.75]);
/// ```
pub fn sobol_sequence(n: usize, dim: usize) -> Result<Vec<Vec<f64>>, UqError> {
    if dim == 0 {
        return Err(UqError::OutOfRange(
            "Sobol' sequence needs dim >= 1 (got 0)".into(),
        ));
    }
    if dim > MAX_DIM {
        return Err(UqError::OutOfRange(format!(
            "Sobol' sequence supports up to {MAX_DIM} dimensions (got {dim}); \
             vendor more Joe–Kuo direction integers to raise the limit"
        )));
    }

    // Per-dimension direction numbers v_k, k = 1..=NUM_BITS, stored as the
    // integer numerator over 2^NUM_BITS (i.e. v_k already shifted so bit 31 is
    // the leading 1/2 place).
    let directions: Vec<[u32; NUM_BITS]> = (0..dim).map(direction_numbers).collect();

    let mut points = Vec::with_capacity(n);
    // x[j] holds the running XOR accumulator for dimension j (an integer in
    // [0, 2^NUM_BITS); divide by 2^NUM_BITS for the coordinate).
    let mut x = vec![0u32; dim];
    let scale = 1.0 / (2f64.powi(NUM_BITS as i32));

    for i in 0..n {
        // Point i is built from point i-1 by XOR-ing the direction number of
        // the lowest *zero* bit of (i-1) — the standard incremental Sobol'
        // update. Index 0 is the all-zero origin.
        if i > 0 {
            let c = lowest_zero_bit(i - 1); // 0-based bit position
            for j in 0..dim {
                x[j] ^= directions[j][c];
            }
        }
        points.push(x.iter().map(|&xi| xi as f64 * scale).collect());
    }
    Ok(points)
}

/// Position (0-based) of the lowest zero bit of `value` — equivalently the
/// number of trailing one-bits. For the Sobol' recurrence this selects which
/// direction number advances the sequence from index `value` to `value + 1`.
fn lowest_zero_bit(value: usize) -> usize {
    (!value).trailing_zeros() as usize
}

/// Build the `NUM_BITS` direction numbers for dimension `j` (0-based).
///
/// Dimension 0 is the van der Corput base-2 sequence: `v_k = 2^(NUM_BITS-k)`,
/// i.e. successive single bits from the top. Every other dimension uses its
/// primitive polynomial (degree `s`, coefficients `a`) and `s` published
/// initial direction integers `m_k` (odd, `m_k < 2^k`); the remaining `m_k` are
/// produced by the Sobol' recurrence, then shifted into place as
/// `v_k = m_k << (NUM_BITS - k)`.
fn direction_numbers(j: usize) -> [u32; NUM_BITS] {
    let mut v = [0u32; NUM_BITS];
    if j == 0 {
        for (k, slot) in v.iter_mut().enumerate() {
            // v_{k+1} = 2^(NUM_BITS-(k+1)); k is 0-based here.
            *slot = 1u32 << (NUM_BITS - 1 - k);
        }
        return v;
    }

    let (degree, a, m_init) = JOE_KUO[j - 1];
    let s = degree;

    // m_1..m_s are given; place them.
    let mut m = [0u64; NUM_BITS + 1]; // 1-based indexing, m[0] unused
    for (k, &mk) in m_init.iter().take(s).enumerate() {
        m[k + 1] = mk as u64;
    }
    // Sobol' recurrence for m_k, k > s:
    //   m_k = 2^1 a_1 m_{k-1} ⊕ 2^2 a_2 m_{k-2} ⊕ … ⊕ 2^{s-1} a_{s-1} m_{k-s+1}
    //         ⊕ 2^s m_{k-s} ⊕ m_{k-s}
    for k in (s + 1)..=NUM_BITS {
        let mut value = m[k - s] ^ (m[k - s] << s);
        for i in 1..s {
            // a is the bit string a_1..a_{s-1}; bit (i-1) (MSB first) is a_i.
            let a_i = (a >> (s - 1 - i)) & 1;
            if a_i == 1 {
                value ^= m[k - i] << i;
            }
        }
        m[k] = value;
    }

    // v_k = m_k << (NUM_BITS - k)  (k is 1-based).
    for k in 1..=NUM_BITS {
        v[k - 1] = (m[k] << (NUM_BITS - k)) as u32;
    }
    v
}

/// Joe–Kuo `new-joe-kuo-6.21201` direction-integer table for dimensions
/// `2..=MAX_DIM` (dimension 1 is the special van der Corput case, handled
/// separately). Each entry is `(s, a, [m_1, …])` where `s` is the degree of the
/// primitive polynomial, `a` encodes its interior coefficients `a_1..a_{s-1}`
/// as a bit string (MSB = `a_1`), and the `m` array lists the `s` published
/// initial direction integers. Public-domain data from
/// <https://web.maths.unsw.edu.au/~fkuo/sobol/>.
const JOE_KUO: [(usize, u64, [u32; 8]); MAX_DIM - 1] = [
    // dim 2
    (1, 0, [1, 0, 0, 0, 0, 0, 0, 0]),
    // dim 3
    (2, 1, [1, 3, 0, 0, 0, 0, 0, 0]),
    // dim 4
    (3, 1, [1, 3, 1, 0, 0, 0, 0, 0]),
    // dim 5
    (3, 2, [1, 1, 1, 0, 0, 0, 0, 0]),
    // dim 6
    (4, 1, [1, 1, 3, 3, 0, 0, 0, 0]),
    // dim 7
    (4, 4, [1, 3, 5, 13, 0, 0, 0, 0]),
    // dim 8
    (5, 2, [1, 1, 5, 5, 17, 0, 0, 0]),
    // dim 9
    (5, 4, [1, 1, 5, 5, 5, 0, 0, 0]),
    // dim 10
    (5, 7, [1, 1, 7, 11, 19, 0, 0, 0]),
    // dim 11
    (5, 11, [1, 1, 5, 1, 1, 0, 0, 0]),
    // dim 12
    (5, 13, [1, 1, 1, 3, 11, 0, 0, 0]),
    // dim 13
    (5, 14, [1, 3, 5, 5, 31, 0, 0, 0]),
    // dim 14
    (6, 1, [1, 3, 3, 9, 7, 49, 0, 0]),
    // dim 15
    (6, 13, [1, 1, 1, 15, 21, 21, 0, 0]),
    // dim 16
    (6, 16, [1, 3, 1, 13, 27, 49, 0, 0]),
    // dim 17
    (6, 19, [1, 1, 1, 15, 7, 5, 0, 0]),
    // dim 18
    (6, 22, [1, 3, 1, 15, 13, 25, 0, 0]),
    // dim 19
    (6, 25, [1, 1, 5, 5, 19, 61, 0, 0]),
    // dim 20
    (7, 1, [1, 3, 7, 11, 23, 39, 65, 0]),
    // dim 21
    (7, 4, [1, 3, 7, 13, 31, 15, 17, 0]),
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Dimension 1 (Gray-code recurrence with `v_k = 2^(32-k)`) emits the dyadic
    /// rationals in the conventional Sobol' order
    /// `0, ½, ¾, ¼, ⅜, ⅞, ⅝, ⅛`. These are exact dyadic rationals, so the
    /// comparison is exact. (Verified against a standard reference
    /// Bratley–Fox/Joe–Kuo generator.)
    #[test]
    fn dim1_gray_code_sequence() {
        let pts = sobol_sequence(8, 1).unwrap();
        let got: Vec<f64> = pts.iter().map(|p| p[0]).collect();
        let want = [0.0, 0.5, 0.75, 0.25, 0.375, 0.875, 0.625, 0.125];
        assert_eq!(got, want);
    }

    /// First Sobol' points in 2-D against the textbook values (Bratley & Fox
    /// 1988, ACM TOMS Alg. 659; reproduced in every Sobol' reference). The
    /// values are exact dyadic rationals.
    #[test]
    fn first_points_2d_match_known_values() {
        let pts = sobol_sequence(8, 2).unwrap();
        let want = [
            [0.0, 0.0],
            [0.5, 0.5],
            [0.75, 0.25],
            [0.25, 0.75],
            [0.375, 0.375],
            [0.875, 0.875],
            [0.625, 0.125],
            [0.125, 0.625],
        ];
        for (p, w) in pts.iter().zip(want.iter()) {
            assert_eq!(p.as_slice(), w.as_slice());
        }
    }

    /// First Sobol' points in 3-D. The third coordinate uses the standard
    /// Joe–Kuo dim-3 direction numbers (primitive polynomial x²+x+1,
    /// m = [1, 3]); under the Gray-code recurrence it emits
    /// `0, ½, ¼, ¾, ⅝, ⅛, ⅞, ⅜`. (Verified against a standard reference
    /// generator.)
    #[test]
    fn first_points_3d_match_known_values() {
        let pts = sobol_sequence(8, 3).unwrap();
        let third: Vec<f64> = pts.iter().map(|p| p[2]).collect();
        let want = [0.0, 0.5, 0.25, 0.75, 0.625, 0.125, 0.875, 0.375];
        assert_eq!(third, want);
    }

    /// Every coordinate of every point must lie in `[0, 1)`.
    #[test]
    fn all_coordinates_in_unit_interval() {
        let pts = sobol_sequence(1000, 5).unwrap();
        for p in &pts {
            assert_eq!(p.len(), 5);
            for &c in p {
                assert!((0.0..1.0).contains(&c), "coordinate {c} out of [0,1)");
            }
        }
    }

    /// Prefix property: the first `m` points of an `n`-point sequence equal a
    /// freshly generated `m`-point sequence.
    #[test]
    fn prefix_property() {
        let long = sobol_sequence(256, 4).unwrap();
        let short = sobol_sequence(32, 4).unwrap();
        assert_eq!(&long[..32], short.as_slice());
    }

    /// QMC with the Sobol' sequence integrates a smooth integrand more
    /// accurately than plain Monte-Carlo at the **same** number of points.
    ///
    /// Test integrand: f(x, y) = exp(x + y) on [0,1]², whose exact integral is
    /// (e − 1)². We compare the Sobol' (QMC) error to a seeded Monte-Carlo
    /// error at the same n; the QMC error must be strictly smaller.
    #[test]
    fn qmc_beats_mc_on_smooth_integrand() {
        use crate::rng::SplitMix64;
        let n = 4096;
        let exact = (std::f64::consts::E - 1.0).powi(2);

        // Quasi-Monte-Carlo with Sobol' points (skip index 0, the origin, which
        // is a corner and biases tiny samples; standard practice).
        let pts = sobol_sequence(n + 1, 2).unwrap();
        let qmc: f64 = pts[1..].iter().map(|p| (p[0] + p[1]).exp()).sum::<f64>() / n as f64;
        let qmc_err = (qmc - exact).abs();

        // Plain Monte-Carlo at the same n, fixed seed.
        let mut rng = SplitMix64::new(0xABCD_1234);
        let mc: f64 = (0..n)
            .map(|_| {
                let x = rng.next_f64();
                let y = rng.next_f64();
                (x + y).exp()
            })
            .sum::<f64>()
            / n as f64;
        let mc_err = (mc - exact).abs();

        assert!(
            qmc_err < mc_err,
            "expected QMC error ({qmc_err:e}) < MC error ({mc_err:e})"
        );
    }

    #[test]
    fn rejects_zero_and_oversized_dim() {
        assert!(sobol_sequence(10, 0).is_err());
        assert!(sobol_sequence(10, MAX_DIM + 1).is_err());
        // The boundary dimension is accepted.
        assert!(sobol_sequence(4, MAX_DIM).is_ok());
    }
}
