//! Generate the Octave / MATLAB script openEMS consumes. Same
//! deterministic-emitter pattern as FreeCAD + Cantera; the
//! generated file is self-contained so users can inspect (and
//! hand-edit outside Valenx) without mystery includes.

use std::fmt::Write;
use std::fs;
use std::io;
use std::path::Path;

use crate::case_input::{Domain, EmInput, Excitation};

pub const SCRIPT_FILENAME: &str = "valenx_openems.m";
pub const SIM_DIR: &str = "sim";

pub fn generate(input: &EmInput) -> String {
    let mut s = String::with_capacity(2048);

    writeln!(
        s,
        "%% Generated by valenx-adapter-openems — do not edit by hand.\n\
         %% prepare() overwrites this file every run."
    )
    .unwrap();
    writeln!(s, "clear all; close all;").unwrap();
    writeln!(s, "physical_constants;").unwrap();
    writeln!(s).unwrap();

    // Domain bounds + cell size.
    let (min, max, cell_size) = match &input.domain {
        Domain::Box {
            min,
            max,
            cell_size,
        } => (*min, *max, *cell_size),
    };
    writeln!(s, "%% Domain").unwrap();
    writeln!(
        s,
        "mesh_size = {cell_size}; % metres\n\
         xmin = {}; ymin = {}; zmin = {};\n\
         xmax = {}; ymax = {}; zmax = {};",
        min[0], min[1], min[2], max[0], max[1], max[2],
    )
    .unwrap();
    writeln!(s).unwrap();

    // Excitation — pick center freq / bandwidth for Gauss, or f0 for Sine.
    writeln!(s, "%% Excitation").unwrap();
    match input.excitation {
        Excitation::Gauss {
            center_freq_hz,
            bandwidth_hz,
        } => {
            writeln!(
                s,
                "f0 = {center_freq_hz}; fc = {bandwidth_hz};\n\
                 FDTD = InitFDTD('NrTS', 1e6, 'EndCriteria', {end}, ...\n    \
                 'OverSampling', 6);\n\
                 FDTD = SetGaussExcite(FDTD, f0, fc);",
                end = input.simulation.end_criterion
            )
            .unwrap();
        }
        Excitation::Sine { freq_hz } => {
            writeln!(
                s,
                "f0 = {freq_hz};\n\
                 FDTD = InitFDTD('NrTS', 1e6, 'EndCriteria', {end});\n\
                 FDTD = SetSinusExcite(FDTD, f0);",
                end = input.simulation.end_criterion
            )
            .unwrap();
        }
    }
    writeln!(s).unwrap();

    // Boundary conditions. openEMS takes a 6-element cellstring
    // (+X -X +Y -Y +Z -Z).
    let bc_keyword = input.boundary.octave_keyword();
    writeln!(s, "%% Boundary conditions").unwrap();
    writeln!(
        s,
        "BC = {{'{bc_keyword}', '{bc_keyword}', '{bc_keyword}', \
         '{bc_keyword}', '{bc_keyword}', '{bc_keyword}'}};\n\
         FDTD = SetBoundaryCond(FDTD, BC);"
    )
    .unwrap();
    writeln!(s).unwrap();

    // CSXCAD setup — grid.
    writeln!(s, "%% Grid").unwrap();
    writeln!(s, "CSX = InitCSX();").unwrap();
    writeln!(
        s,
        "CSX = DefineRectGrid(CSX, mesh_size, struct(\n    \
             'X', xmin:mesh_size:xmax,\n    \
             'Y', ymin:mesh_size:ymax,\n    \
             'Z', zmin:mesh_size:zmax));"
    )
    .unwrap();
    writeln!(s).unwrap();

    // Probes for post-processing.
    if !input.probes.is_empty() {
        writeln!(s, "%% Probes").unwrap();
        for (i, probe) in input.probes.iter().enumerate() {
            let name = sanitise_octave_name(&probe.name);
            writeln!(
                s,
                "CSX = AddProbe(CSX, '{name}', 0);\n\
                 CSX = AddBox(CSX, '{name}', {priority}, \
                              [{x} {y} {z}], [{x} {y} {z}]);",
                priority = i,
                x = probe.position[0],
                y = probe.position[1],
                z = probe.position[2],
            )
            .unwrap();
        }
        writeln!(s).unwrap();
    }

    // Run.
    writeln!(s, "%% Run FDTD").unwrap();
    writeln!(s, "Sim_Path = '{SIM_DIR}';").unwrap();
    writeln!(s, "[status, message, ~] = rmdir(Sim_Path, 's');").unwrap();
    writeln!(s, "mkdir(Sim_Path);").unwrap();
    writeln!(
        s,
        "WriteOpenEMS(fullfile(Sim_Path, 'fdtd.xml'), FDTD, CSX);\n\
         RunOpenEMS(Sim_Path, 'fdtd.xml');"
    )
    .unwrap();
    writeln!(s).unwrap();

    // Post-processing: dump every probe's time-domain trace as CSV
    // so the canonical collect() can read it without an HDF5
    // dependency. openEMS stores probe data under `<sim>/<name>` as
    // `.h5`; ReadUI_Data extracts it into Octave structs we then
    // write as `<sim>/<name>.csv`. Wrapped in try/catch so a single
    // missing probe doesn't abort the whole post-processing block.
    writeln!(s, "%% Post").unwrap();
    for probe in &input.probes {
        let name = sanitise_octave_name(&probe.name);
        writeln!(
            s,
            "try\n  \
               ui = ReadUI_Data({{'{name}'}}, Sim_Path, [], 'AR', 1);\n  \
               if isfield(ui, 'TD') && length(ui.TD) >= 1 && \
                   isfield(ui.TD{{1}}, 't')\n    \
                 fid = fopen(fullfile(Sim_Path, '{name}.csv'), 'w');\n    \
                 fprintf(fid, 't_s,value\\n');\n    \
                 for k = 1:length(ui.TD{{1}}.t)\n      \
                   fprintf(fid, '%g,%g\\n', ui.TD{{1}}.t(k), ui.TD{{1}}.val(k));\n    \
                 end\n    \
                 fclose(fid);\n    \
                 disp(sprintf('[valenx] wrote probe csv: {name}'));\n  \
               end\n\
             catch err\n  \
               disp(sprintf('[valenx] probe {name} export failed: %s', err.message));\n\
             end"
        )
        .unwrap();
    }
    writeln!(
        s,
        "disp(sprintf('[valenx] openEMS finished; sim path = %s', Sim_Path));"
    )
    .unwrap();

    s
}

pub fn write_to_file(input: &EmInput, path: &Path) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    valenx_core::io_caps::atomic_write_str(path, &generate(input))
}

/// Octave identifiers allow letters, digits, underscore, and no
/// leading digit. Strip everything else.
fn sanitise_octave_name(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_alphanumeric() || c == '_' {
            if i == 0 && c.is_ascii_digit() {
                out.push('_');
            }
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "probe".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::case_input::{BoundaryCondition, Domain, EmInput, Excitation, Probe, Simulation};

    fn gauss_input() -> EmInput {
        EmInput {
            domain: Domain::Box {
                min: [-0.05, -0.05, -0.05],
                max: [0.05, 0.05, 0.05],
                cell_size: 0.002,
            },
            excitation: Excitation::Gauss {
                center_freq_hz: 5e9,
                bandwidth_hz: 5e9,
            },
            simulation: Simulation {
                sim_time_s: 10e-9,
                end_criterion: 1e-3,
                post_freqs: vec![5e9],
            },
            boundary: BoundaryCondition::Pml,
            probes: vec![Probe {
                name: "center".into(),
                position: [0.0, 0.0, 0.0],
                component: "E_z".into(),
            }],
        }
    }

    #[test]
    fn octave_script_has_expected_pieces() {
        let s = generate(&gauss_input());
        assert!(s.contains("InitFDTD("));
        assert!(s.contains("SetGaussExcite(FDTD, f0, fc)"));
        assert!(s.contains("mesh_size = 0.002"));
        assert!(s.contains("'PML_8', 'PML_8'"));
        assert!(s.contains("AddProbe(CSX, 'center'"));
        assert!(s.contains("WriteOpenEMS"));
        assert!(s.contains("RunOpenEMS"));
    }

    #[test]
    fn sine_excitation_uses_sine_card() {
        let mut input = gauss_input();
        input.excitation = Excitation::Sine { freq_hz: 2.4e9 };
        let s = generate(&input);
        assert!(s.contains("SetSinusExcite(FDTD, f0)"));
        assert!(!s.contains("SetGaussExcite"));
    }

    #[test]
    fn sanitise_octave_name_strips_illegal() {
        assert_eq!(sanitise_octave_name("probe"), "probe");
        assert_eq!(sanitise_octave_name("my probe"), "my_probe");
        assert_eq!(sanitise_octave_name("1st"), "_1st");
        assert_eq!(sanitise_octave_name(""), "probe");
    }

    #[test]
    fn boundary_keyword_matches_enum() {
        assert_eq!(BoundaryCondition::Pml.octave_keyword(), "PML_8");
        assert_eq!(BoundaryCondition::Mur.octave_keyword(), "MUR");
        assert_eq!(BoundaryCondition::Pec.octave_keyword(), "PEC");
    }
}
